package com.titanops.vista;

import com.titanops.controlador.LoginController;
import com.titanops.dao.RolDAO;
import com.titanops.dao.UsuarioDAO;
import com.titanops.modelo.Rol;
import com.titanops.modelo.Usuario;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aleyt
 */
public class FILES extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FILES.class.getName());
    private Usuario usuarioAutenticado;
    private LOGIN loginActivo;
    private LoginController loginController;
    private javax.swing.JLabel logoTitan;

    public FILES() {
        initComponents();


        configurarLogoTitan();
        setSize(1000, 700);
        setLocationRelativeTo(null);
        setTitle("TitanOps");
        configurarAccesos(null);
        java.awt.EventQueue.invokeLater(this::mostrarLogin);
    }

    private void configurarLogoTitan() {
        jDesktopPane1.setLayout(null);
        logoTitan = new javax.swing.JLabel(new javax.swing.ImageIcon(
                getClass().getResource("/multimedia/LOGOSINFONDOPEQUELO.png")));
        logoTitan.setHorizontalAlignment(SwingConstants.CENTER);
        logoTitan.setVerticalAlignment(SwingConstants.CENTER);
        logoTitan.setOpaque(false);
        jDesktopPane1.add(logoTitan, JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent event) {
                logoTitan.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
            }
        });
        logoTitan.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNavegacion = new javax.swing.JPanel();
        panelModulos = new javax.swing.JPanel();
        btnUsuarios = new com.titanops.vista.componentes.Boton();
        btnMaquinaria = new com.titanops.vista.componentes.Boton();
        btnCategorias = new com.titanops.vista.componentes.Boton();
        btnOperadores = new com.titanops.vista.componentes.Boton();
        btnRutas = new com.titanops.vista.componentes.Boton();
        btnReportes = new com.titanops.vista.componentes.Boton();
        btnSesion = new com.titanops.vista.componentes.Boton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));

        panelNavegacion.setBackground(new java.awt.Color(239, 246, 255));
        panelNavegacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 8, 6, 8));
        panelNavegacion.setLayout(new java.awt.BorderLayout(8, 0));

        panelModulos.setOpaque(false);
        panelModulos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 0));

        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBackground(new java.awt.Color(239, 246, 255));
        btnUsuarios.setForeground(new java.awt.Color(30, 64, 175));
        btnUsuarios.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnUsuarios.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnUsuarios.setColorFoco(new java.awt.Color(37, 99, 235));
        btnUsuarios.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnUsuarios.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1),
            javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        btnUsuarios.setRolloverEnabled(true);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setOpaque(false);
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);
        panelModulos.add(btnUsuarios);

        btnMaquinaria.setText("Maquinaria");
        btnMaquinaria.setBackground(new java.awt.Color(239, 246, 255));
        btnMaquinaria.setForeground(new java.awt.Color(30, 64, 175));
        btnMaquinaria.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnMaquinaria.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnMaquinaria.setColorFoco(new java.awt.Color(37, 99, 235));
        btnMaquinaria.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnMaquinaria.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1),
            javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        btnMaquinaria.setRolloverEnabled(true);
        btnMaquinaria.setContentAreaFilled(false);
        btnMaquinaria.setOpaque(false);
        btnMaquinaria.addActionListener(this::btnMaquinariaActionPerformed);
        panelModulos.add(btnMaquinaria);

        btnCategorias.setText("Categorías");
        btnCategorias.setBackground(new java.awt.Color(239, 246, 255));
        btnCategorias.setForeground(new java.awt.Color(30, 64, 175));
        btnCategorias.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnCategorias.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnCategorias.setColorFoco(new java.awt.Color(37, 99, 235));
        btnCategorias.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnCategorias.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1),
            javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        btnCategorias.setRolloverEnabled(true);
        btnCategorias.setContentAreaFilled(false);
        btnCategorias.setOpaque(false);
        btnCategorias.addActionListener(this::btnCategoriasActionPerformed);
        panelModulos.add(btnCategorias);

        btnOperadores.setText("Operadores");
        btnOperadores.setBackground(new java.awt.Color(239, 246, 255));
        btnOperadores.setForeground(new java.awt.Color(30, 64, 175));
        btnOperadores.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnOperadores.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnOperadores.setColorFoco(new java.awt.Color(37, 99, 235));
        btnOperadores.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnOperadores.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1),
            javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        btnOperadores.setRolloverEnabled(true);
        btnOperadores.setContentAreaFilled(false);
        btnOperadores.setOpaque(false);
        btnOperadores.addActionListener(this::btnOperadoresActionPerformed);
        panelModulos.add(btnOperadores);

        btnRutas.setText("Rutas");
        btnRutas.setBackground(new java.awt.Color(239, 246, 255));
        btnRutas.setForeground(new java.awt.Color(30, 64, 175));
        btnRutas.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnRutas.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnRutas.setColorFoco(new java.awt.Color(37, 99, 235));
        btnRutas.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnRutas.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1),
            javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        btnRutas.setRolloverEnabled(true);
        btnRutas.setContentAreaFilled(false);
        btnRutas.setOpaque(false);
        btnRutas.addActionListener(this::btnRutasActionPerformed);
        panelModulos.add(btnRutas);

        btnReportes.setText("Control y reportes");
        btnReportes.setBackground(new java.awt.Color(239, 246, 255));
        btnReportes.setForeground(new java.awt.Color(30, 64, 175));
        btnReportes.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnReportes.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnReportes.setColorFoco(new java.awt.Color(37, 99, 235));
        btnReportes.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnReportes.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1),
            javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        btnReportes.setRolloverEnabled(true);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setOpaque(false);
        btnReportes.addActionListener(this::btnReportesActionPerformed);
        panelModulos.add(btnReportes);

        panelNavegacion.add(panelModulos, java.awt.BorderLayout.WEST);

        btnSesion.setText("Iniciar sesión");
        btnSesion.setBackground(new java.awt.Color(239, 246, 255));
        btnSesion.setForeground(new java.awt.Color(30, 64, 175));
        btnSesion.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnSesion.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnSesion.setColorFoco(new java.awt.Color(37, 99, 235));
        btnSesion.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnSesion.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1),
            javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        btnSesion.setRolloverEnabled(true);
        btnSesion.setContentAreaFilled(false);
        btnSesion.setOpaque(false);
        btnSesion.addActionListener(this::btnSesionActionPerformed);
        panelNavegacion.add(btnSesion, java.awt.BorderLayout.EAST);

        jDesktopPane1.setForeground(new java.awt.Color(30, 41, 59));
        jDesktopPane1.setBackground(new java.awt.Color(239, 246, 255));
        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelNavegacion, java.awt.BorderLayout.NORTH);
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        System.out.println("1. CLICK");

        GESTIONUS1 panta = new GESTIONUS1(
                jDesktopPane1,
                usuarioAutenticado == null ? null : usuarioAutenticado.getIdUsuario());

      

        jDesktopPane1.add(panta);

        panta.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnMaquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquinariaActionPerformed

        MAQUINARIAGESTION panta = new MAQUINARIAGESTION(jDesktopPane1);

    

        jDesktopPane1.add(panta);

        panta.setVisible(true);
    }//GEN-LAST:event_btnMaquinariaActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        GestionCategorias panta = new GestionCategorias();
        jDesktopPane1.add(panta);
        panta.setLocation(20, 20);
        panta.setVisible(true);
        panta.toFront();
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Control_y_reportes panta = new Control_y_reportes(
                jDesktopPane1,
                usuarioAutenticado == null ? null : usuarioAutenticado.getIdUsuario());
        jDesktopPane1.add(panta);
        panta.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutasActionPerformed
       Rutas panta = new Rutas(
               usuarioAutenticado == null ? null : usuarioAutenticado.getIdUsuario());
       jDesktopPane1.add(panta);
       panta.setVisible(true);
    }//GEN-LAST:event_btnRutasActionPerformed

    private void btnOperadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperadoresActionPerformed
       Gestion_de_operadores panta = new Gestion_de_operadores();
       jDesktopPane1.add(panta);
       panta.setVisible(true);
    }//GEN-LAST:event_btnOperadoresActionPerformed

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        if (usuarioAutenticado == null) {
            mostrarLogin();
        } else {
            cerrarSesion();
        }
    }//GEN-LAST:event_btnSesionActionPerformed

    private void mostrarLogin() {
        if (loginActivo != null && !loginActivo.isClosed()) {
            loginActivo.setVisible(true);
            loginActivo.toFront();
            return;
        }

        loginActivo = new LOGIN();
        loginController = new LoginController(
                loginActivo, new UsuarioDAO(), new RolDAO(), this::iniciarSesion);
        jDesktopPane1.add(loginActivo);

        int x = Math.max(0, (jDesktopPane1.getWidth() - loginActivo.getWidth()) / 2);
        int y = Math.max(0, (jDesktopPane1.getHeight() - loginActivo.getHeight()) / 2);
        loginActivo.setLocation(x, y);
        loginActivo.setVisible(true);
        loginActivo.toFront();
    }

    private void iniciarSesion(Usuario usuario, Rol rol) {
        usuarioAutenticado = usuario;
        loginActivo = null;
        configurarAccesos(rol);
        setTitle("TitanOps - " + usuario.getNombreCompleto() + " - " + rol.getNombreRol());
        JOptionPane.showMessageDialog(this,
                "Bienvenido, " + usuario.getNombreCompleto() + ".",
                "Sesión iniciada", JOptionPane.INFORMATION_MESSAGE);
    }

    private void configurarAccesos(Rol rol) {
        boolean autenticado = rol != null;
        boolean administrador = autenticado
                && "ADMINISTRADOR".equalsIgnoreCase(rol.getNombreRol());
        boolean operadorDespacho = autenticado
                && "OPERADOR_DESPACHO".equalsIgnoreCase(rol.getNombreRol());
        boolean accesoOperativo = administrador || operadorDespacho;

        btnSesion.setText(autenticado ? "Cerrar sesión" : "Iniciar sesión");
        btnUsuarios.setEnabled(administrador);
        btnMaquinaria.setEnabled(accesoOperativo);
        btnCategorias.setEnabled(administrador);
        btnReportes.setEnabled(accesoOperativo);
        btnRutas.setEnabled(accesoOperativo);
        btnOperadores.setEnabled(accesoOperativo);
    }

    private void cerrarSesion() {
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Deseas cerrar la sesión actual?", "Cerrar sesión",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            frame.dispose();
        }

        usuarioAutenticado = null;
        loginActivo = null;
        loginController = null;
        configurarAccesos(null);
        setTitle("TitanOps");
        mostrarLogin();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FILES().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.titanops.vista.componentes.Boton btnCategorias;
    private com.titanops.vista.componentes.Boton btnMaquinaria;
    private com.titanops.vista.componentes.Boton btnOperadores;
    private com.titanops.vista.componentes.Boton btnReportes;
    private com.titanops.vista.componentes.Boton btnRutas;
    private com.titanops.vista.componentes.Boton btnSesion;
    private com.titanops.vista.componentes.Boton btnUsuarios;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel panelModulos;
    private javax.swing.JPanel panelNavegacion;
    // End of variables declaration//GEN-END:variables
}
