package com.titanops.vista;

import com.titanops.controlador.GestionUsuariosController;
import com.titanops.controlador.GestionUsuariosController.ResultadoOperacion;
import com.titanops.controlador.GestionUsuariosController.UsuarioFila;
import com.titanops.dao.RolDAO;
import com.titanops.dao.UsuarioDAO;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/Systorigin/samuel-cambiosemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author aleyt
 */
public class GESTIONUS extends javax.swing.JInternalFrame {

    private static final DateTimeFormatter FORMATO_FECHA =
            DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    private final GestionUsuariosController controller;
    private final Integer idUsuarioSesion;
    private boolean cargando;
    private boolean recargaPendiente;

    /**
     * Creates new form PLANTILLA4
     */
    public GESTIONUS() {
        this((Integer) null);
    }

    public GESTIONUS(Integer idUsuarioSesion) {
        this(idUsuarioSesion, new GestionUsuariosController(new UsuarioDAO(), new RolDAO()));
    }

    GESTIONUS(Integer idUsuarioSesion, GestionUsuariosController controller) {
        initComponents();
        this.idUsuarioSesion = idUsuarioSesion;
        this.controller = controller;
        configurarVista();

        recargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new com.titanops.vista.componentes.Tabla();
        GUARDARUS = new com.titanops.vista.componentes.Boton();
        GUARDARUS1 = new com.titanops.vista.componentes.Boton();
        GUARDARUS2 = new com.titanops.vista.componentes.Boton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);



        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 50)); // NOI18N
        jLabel1.setText("Gestión de Usuarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre completo", "Usuario", "Rol", "Estado", "Fecha de creación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        GUARDARUS.setBackground(new java.awt.Color(37, 99, 235));
        GUARDARUS.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        GUARDARUS.setForeground(new java.awt.Color(255, 255, 255));
        GUARDARUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ELIMINARPEQUEÑO.png"))); // NOI18N
        GUARDARUS.setText("DESACTIVAR");
        GUARDARUS.setBorder(null);

        GUARDARUS1.setBackground(new java.awt.Color(37, 99, 235));
        GUARDARUS1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        GUARDARUS1.setForeground(new java.awt.Color(255, 255, 255));
        GUARDARUS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/NUEVOPEQUEÑO.png"))); // NOI18N
        GUARDARUS1.setText("CREAR");
        GUARDARUS1.setBorder(null);

        GUARDARUS2.setBackground(new java.awt.Color(37, 99, 235));
        GUARDARUS2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        GUARDARUS2.setForeground(new java.awt.Color(255, 255, 255));
        GUARDARUS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/EDITARPEQUEÑO.png"))); // NOI18N
        GUARDARUS2.setText("EDITAR");
        GUARDARUS2.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(GUARDARUS1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GUARDARUS2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GUARDARUS))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUARDARUS1)
                    .addComponent(GUARDARUS2)
                    .addComponent(GUARDARUS))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );


        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        jPanel1.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.setBackground(new java.awt.Color(239, 246, 255));
        jPanel2.setForeground(new java.awt.Color(30, 41, 59));
        jPanel2.setBackground(new java.awt.Color(30, 64, 175));
        jScrollPane1.setForeground(new java.awt.Color(30, 41, 59));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1));
        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));


        jPanel1.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.setBackground(new java.awt.Color(239, 246, 255));
        jPanel2.setForeground(new java.awt.Color(30, 41, 59));
        jPanel2.setBackground(new java.awt.Color(30, 64, 175));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 50));
        jLabel1.setText("Gestión de Usuarios");
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(30, 41, 59));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1));
        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(30, 41, 59));
        jTable1.setGridColor(new java.awt.Color(125, 211, 252));
        jTable1.setSelectionBackground(new java.awt.Color(219, 234, 254));
        jTable1.setSelectionForeground(new java.awt.Color(30, 64, 175));
        jTable1.setFondoCabecera(new java.awt.Color(224, 242, 254));
        jTable1.setTextoCabecera(new java.awt.Color(30, 64, 175));
        jTable1.setBordeCabecera(new java.awt.Color(125, 211, 252));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1));
        jTable1.setFont(new java.awt.Font("SansSerif", 0, 13));
        jTable1.setRowHeight(30);
        jTable1.setShowVerticalLines(false);
        jTable1.setFillsViewportHeight(true);
        GUARDARUS.setText("DESACTIVAR");
        GUARDARUS.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS.setFont(new java.awt.Font("SansSerif", 1, 13));
        GUARDARUS.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS.setRolloverEnabled(true);
        GUARDARUS.setContentAreaFilled(false);
        GUARDARUS.setOpaque(false);
        GUARDARUS1.setText("CREAR");
        GUARDARUS1.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS1.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS1.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS1.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS1.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS1.setFont(new java.awt.Font("SansSerif", 1, 13));
        GUARDARUS1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS1.setRolloverEnabled(true);
        GUARDARUS1.setContentAreaFilled(false);
        GUARDARUS1.setOpaque(false);
        GUARDARUS2.setText("EDITAR");
        GUARDARUS2.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS2.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS2.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS2.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS2.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS2.setFont(new java.awt.Font("SansSerif", 1, 13));
        GUARDARUS2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS2.setRolloverEnabled(true);
        GUARDARUS2.setContentAreaFilled(false);
        GUARDARUS2.setOpaque(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVista() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ID", "Nombre completo", "Usuario", "Rol", "Estado",
                    "Fecha de creación"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(modelo);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.getTableHeader().setReorderingAllowed(false);

        GUARDARUS1.addActionListener(event -> abrirCrearUsuario());
        GUARDARUS2.addActionListener(event -> abrirEditarUsuario());
        GUARDARUS.addActionListener(event -> cambiarEstadoSeleccionado());
        jTable1.getSelectionModel().addListSelectionListener(
                event -> actualizarBotonesSeleccion());
        GUARDARUS2.setEnabled(false);
        GUARDARUS.setEnabled(false);
    }

    public final void recargarUsuarios() {
        if (cargando) {
            recargaPendiente = true;
            return;
        }
        cargando = true;
        GUARDARUS1.setEnabled(false);

        new SwingWorker<List<UsuarioFila>, Void>() {
            @Override
            protected List<UsuarioFila> doInBackground() {
                return controller.listarUsuarios();
            }

            @Override
            protected void done() {
                cargando = false;
                GUARDARUS1.setEnabled(true);
                try {
                    llenarTabla(get());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga de usuarios.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar los usuarios.");
                } finally {
                    if (recargaPendiente) {
                        recargaPendiente = false;
                        recargarUsuarios();
                    }
                }
            }
        }.execute();
    }

    private void llenarTabla(List<UsuarioFila> usuarios) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.clearSelection();
        modelo.setRowCount(0);
        for (UsuarioFila usuario : usuarios) {
            String fecha = usuario.fechaCreacion() == null
                    ? "" : usuario.fechaCreacion().toLocalDateTime().format(FORMATO_FECHA);
            modelo.addRow(new Object[]{
                usuario.idUsuario(),
                usuario.nombreCompleto(),
                usuario.username(),
                usuario.rol(),
                usuario.activo() ? "ACTIVO" : "INACTIVO",
                fecha
            });
        }
        actualizarBotonesSeleccion();
    }

    private void actualizarBotonesSeleccion() {
        int fila = jTable1.getSelectedRow();
        boolean seleccionValida = fila >= 0 && !cargando;
        GUARDARUS2.setEnabled(seleccionValida);
        GUARDARUS.setEnabled(seleccionValida);
        if (!seleccionValida) {
            GUARDARUS.setText("DESACTIVAR");
            return;
        }
        int filaModelo = jTable1.convertRowIndexToModel(fila);
        boolean activo = "ACTIVO".equals(jTable1.getModel().getValueAt(filaModelo, 4));
        GUARDARUS.setText(activo ? "DESACTIVAR" : "REACTIVAR");
    }

    private Integer idUsuarioSeleccionado() {
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            return null;
        }
        int filaModelo = jTable1.convertRowIndexToModel(fila);
        return (Integer) jTable1.getModel().getValueAt(filaModelo, 0);
    }

    private boolean usuarioSeleccionadoActivo() {
        int filaModelo = jTable1.convertRowIndexToModel(jTable1.getSelectedRow());
        return "ACTIVO".equals(jTable1.getModel().getValueAt(filaModelo, 4));
    }

    private void abrirCrearUsuario() {
        javax.swing.JDesktopPane desktop = getDesktopPane();
        if (desktop == null) {
            mostrarError("No se encontró el escritorio principal.");
            return;
        }

        for (JInternalFrame frame : desktop.getAllFrames()) {
            if (frame instanceof GESTIONUS1 formulario) {
                formulario.dispose();
            }
        }

        GESTIONUS1 crearUsuario = new GESTIONUS1(desktop, idUsuarioSesion);
        desktop.add(crearUsuario);
        crearUsuario.setLocation(20, 20);
        crearUsuario.setVisible(true);
        crearUsuario.toFront();
    }

    private void abrirEditarUsuario() {
        Integer idUsuario = idUsuarioSeleccionado();
        if (idUsuario == null) {
            return;
        }
        javax.swing.JDesktopPane desktop = getDesktopPane();
        if (desktop == null) {
            mostrarError("No se encontró el escritorio principal.");
            return;
        }

        for (JInternalFrame frame : desktop.getAllFrames()) {
            if (frame instanceof GESTIONUS1 formulario) {
                formulario.dispose();
            }
        }

        GESTIONUS1 editarUsuario =
                new GESTIONUS1(desktop, idUsuarioSesion, idUsuario);
        desktop.add(editarUsuario);
        editarUsuario.setLocation(20, 20);
        editarUsuario.setVisible(true);
        editarUsuario.toFront();
    }

    private void cambiarEstadoSeleccionado() {
        Integer idUsuario = idUsuarioSeleccionado();
        if (idUsuario == null) {
            return;
        }
        boolean activar = !usuarioSeleccionadoActivo();
        String accion = activar ? "reactivar" : "desactivar";
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Deseas " + accion + " el usuario seleccionado?",
                activar ? "Reactivar usuario" : "Desactivar usuario",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        cargando = true;
        GUARDARUS.setEnabled(false);
        GUARDARUS1.setEnabled(false);
        GUARDARUS2.setEnabled(false);
        new SwingWorker<ResultadoOperacion, Void>() {
            @Override
            protected ResultadoOperacion doInBackground() {
                return controller.cambiarEstadoUsuario(
                        idUsuario, activar, idUsuarioSesion);
            }

            @Override
            protected void done() {
                cargando = false;
                GUARDARUS1.setEnabled(true);
                try {
                    ResultadoOperacion resultado = get();
                    if (!resultado.exitoso()) {
                        JOptionPane.showMessageDialog(GESTIONUS.this, resultado.mensaje(),
                                "Validación", JOptionPane.WARNING_MESSAGE);
                        actualizarBotonesSeleccion();
                        return;
                    }
                    JOptionPane.showMessageDialog(GESTIONUS.this, resultado.mensaje(),
                            "Gestión de usuarios", JOptionPane.INFORMATION_MESSAGE);
                    recargarUsuarios();
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la actualización del usuario.");
                    actualizarBotonesSeleccion();
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible actualizar el estado del usuario.");
                    actualizarBotonesSeleccion();
                }
            }
        }.execute();
    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Gestión de usuarios",
                JOptionPane.ERROR_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.titanops.vista.componentes.Boton GUARDARUS;
    private com.titanops.vista.componentes.Boton GUARDARUS1;
    private com.titanops.vista.componentes.Boton GUARDARUS2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.titanops.vista.componentes.Tabla jTable1;
    // End of variables declaration//GEN-END:variables
}
