package com.titanops.vista;

import com.titanops.controlador.GestionCategoriasController;
import com.titanops.controlador.GestionCategoriasController.CategoriaEdicion;
import com.titanops.controlador.GestionCategoriasController.CategoriaFila;
import com.titanops.controlador.GestionCategoriasController.ResultadoOperacion;
import com.titanops.dao.CategoriaMaquinariaDAO;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/** Vista editable desde NetBeans para administrar categorías de maquinaria. */
public class GestionCategorias extends javax.swing.JInternalFrame {

    private final GestionCategoriasController controller;
    private boolean cargando;
    private boolean recargaPendiente;

    public GestionCategorias() {
        this(new GestionCategoriasController(new CategoriaMaquinariaDAO()));
    }

    GestionCategorias(GestionCategoriasController controller) {
        initComponents();
        this.controller = controller;
        configurarVista();

        recargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelFormulario = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new com.titanops.vista.componentes.CampoTexto();
        lblDescripcion = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new com.titanops.vista.componentes.AreaTexto();
        chkActivo = new javax.swing.JCheckBox();
        btnGuardar = new com.titanops.vista.componentes.Boton();
        txtId = new com.titanops.vista.componentes.CampoTexto();
        panelListado = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new com.titanops.vista.componentes.CampoTexto();
        btnBuscar = new com.titanops.vista.componentes.Boton();
        scrollTabla = new javax.swing.JScrollPane();
        tablaCategorias = new com.titanops.vista.componentes.Tabla();
        btnEditar = new com.titanops.vista.componentes.Boton();
        btnEstado = new com.titanops.vista.componentes.Boton();
        btnRefrescar = new com.titanops.vista.componentes.Boton();
        lblEstado = new javax.swing.JLabel();
        btnNuevo = new com.titanops.vista.componentes.Boton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Administración de categorías");



        lblTitulo.setText("Administración de categorías");

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo)
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo)
        );

        lblId.setText("ID");

        lblNombre.setText("Nombre");

        lblDescripcion.setText("Descripción");

        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        scrollDescripcion.setViewportView(txtDescripcion);

        chkActivo.setText("Categoría activa");

        btnGuardar.setText("GUARDAR");

        txtId.setEditable(false);

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkActivo))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDescripcion)
                    .addComponent(scrollDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkActivo))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        lblBuscar.setText("Buscar");

        btnBuscar.setText("BUSCAR");

        tablaCategorias.setAutoCreateRowSorter(true);
        scrollTabla.setViewportView(tablaCategorias);

        btnEditar.setText("EDITAR");

        btnEstado.setText("DESACTIVAR");

        btnRefrescar.setText("REFRESCAR");

        lblEstado.setText(" ");

        btnNuevo.setText("NUEVO");

        javax.swing.GroupLayout panelListadoLayout = new javax.swing.GroupLayout(panelListado);
        panelListado.setLayout(panelListadoLayout);
        panelListadoLayout.setHorizontalGroup(
            panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListadoLayout.createSequentialGroup()
                        .addGroup(panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelListadoLayout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                                .addGap(92, 92, 92)
                                .addComponent(lblBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListadoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEstado)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefrescar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(62, 62, 62))
                    .addComponent(scrollTabla)))
        );
        panelListadoLayout.setVerticalGroup(
            panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addGroup(panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescar)
                    .addComponent(btnEstado)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );


        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        panelPrincipal.setForeground(new java.awt.Color(30, 41, 59));
        panelPrincipal.setBackground(new java.awt.Color(239, 246, 255));
        panelCabecera.setForeground(new java.awt.Color(30, 41, 59));
        panelCabecera.setBackground(new java.awt.Color(30, 64, 175));
        panelFormulario.setForeground(new java.awt.Color(30, 41, 59));
        panelFormulario.setBackground(new java.awt.Color(248, 250, 252));
        scrollDescripcion.setForeground(new java.awt.Color(30, 41, 59));
        scrollDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1));
        scrollDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        panelListado.setForeground(new java.awt.Color(30, 41, 59));
        panelListado.setBackground(new java.awt.Color(248, 250, 252));
        scrollTabla.setForeground(new java.awt.Color(30, 41, 59));
        scrollTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1));
        scrollTabla.setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 26));
        lblTitulo.setHorizontalAlignment(0);
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        lblId.setForeground(new java.awt.Color(30, 41, 59));
        lblNombre.setForeground(new java.awt.Color(30, 41, 59));
        lblDescripcion.setForeground(new java.awt.Color(30, 41, 59));
        chkActivo.setForeground(new java.awt.Color(30, 41, 59));
        chkActivo.setOpaque(false);
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        lblBuscar.setForeground(new java.awt.Color(30, 41, 59));
        lblEstado.setForeground(new java.awt.Color(30, 41, 59));


        panelPrincipal.setForeground(new java.awt.Color(30, 41, 59));
        panelPrincipal.setBackground(new java.awt.Color(239, 246, 255));
        panelCabecera.setForeground(new java.awt.Color(30, 41, 59));
        panelCabecera.setBackground(new java.awt.Color(30, 64, 175));
        lblTitulo.setText("Administración de categorías");
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 26));
        panelFormulario.setForeground(new java.awt.Color(30, 41, 59));
        panelFormulario.setBackground(new java.awt.Color(248, 250, 252));
        lblId.setText("ID");
        lblId.setForeground(new java.awt.Color(30, 41, 59));
        lblNombre.setText("Nombre");
        lblNombre.setForeground(new java.awt.Color(30, 41, 59));
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(30, 41, 59));
        txtNombre.setColorFoco(new java.awt.Color(37, 99, 235));
        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 13));
        txtNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 40));
        txtNombre.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtNombre.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtNombre.setCaretColor(new java.awt.Color(37, 99, 235));
        txtNombre.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtNombre.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        lblDescripcion.setText("Descripción");
        lblDescripcion.setForeground(new java.awt.Color(30, 41, 59));
        scrollDescripcion.setForeground(new java.awt.Color(30, 41, 59));
        scrollDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1));
        scrollDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setForeground(new java.awt.Color(30, 41, 59));
        txtDescripcion.setColorFoco(new java.awt.Color(37, 99, 235));
        txtDescripcion.setFont(new java.awt.Font("SansSerif", 0, 13));
        txtDescripcion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtDescripcion.setPreferredSize(new java.awt.Dimension(210, 82));
        txtDescripcion.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtDescripcion.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtDescripcion.setCaretColor(new java.awt.Color(37, 99, 235));
        txtDescripcion.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtDescripcion.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        chkActivo.setText("Categoría activa");
        chkActivo.setForeground(new java.awt.Color(30, 41, 59));
        chkActivo.setOpaque(false);
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBackground(new java.awt.Color(239, 246, 255));
        btnGuardar.setForeground(new java.awt.Color(30, 64, 175));
        btnGuardar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnGuardar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnGuardar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnGuardar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnGuardar.setRolloverEnabled(true);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setOpaque(false);
        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setForeground(new java.awt.Color(30, 41, 59));
        txtId.setColorFoco(new java.awt.Color(37, 99, 235));
        txtId.setFont(new java.awt.Font("SansSerif", 0, 13));
        txtId.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtId.setPreferredSize(new java.awt.Dimension(200, 40));
        txtId.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtId.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtId.setCaretColor(new java.awt.Color(37, 99, 235));
        txtId.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtId.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        panelListado.setForeground(new java.awt.Color(30, 41, 59));
        panelListado.setBackground(new java.awt.Color(248, 250, 252));
        lblBuscar.setText("Buscar");
        lblBuscar.setForeground(new java.awt.Color(30, 41, 59));
        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(30, 41, 59));
        txtBuscar.setColorFoco(new java.awt.Color(37, 99, 235));
        txtBuscar.setFont(new java.awt.Font("SansSerif", 0, 13));
        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtBuscar.setPreferredSize(new java.awt.Dimension(200, 40));
        txtBuscar.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtBuscar.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtBuscar.setCaretColor(new java.awt.Color(37, 99, 235));
        txtBuscar.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtBuscar.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBackground(new java.awt.Color(239, 246, 255));
        btnBuscar.setForeground(new java.awt.Color(30, 64, 175));
        btnBuscar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnBuscar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnBuscar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnBuscar.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnBuscar.setRolloverEnabled(true);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setOpaque(false);
        scrollTabla.setForeground(new java.awt.Color(30, 41, 59));
        scrollTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1));
        scrollTabla.setBackground(new java.awt.Color(255, 255, 255));
        tablaCategorias.setBackground(new java.awt.Color(255, 255, 255));
        tablaCategorias.setForeground(new java.awt.Color(30, 41, 59));
        tablaCategorias.setGridColor(new java.awt.Color(125, 211, 252));
        tablaCategorias.setSelectionBackground(new java.awt.Color(219, 234, 254));
        tablaCategorias.setSelectionForeground(new java.awt.Color(30, 64, 175));
        tablaCategorias.setFondoCabecera(new java.awt.Color(224, 242, 254));
        tablaCategorias.setTextoCabecera(new java.awt.Color(30, 64, 175));
        tablaCategorias.setBordeCabecera(new java.awt.Color(125, 211, 252));
        tablaCategorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1));
        tablaCategorias.setFont(new java.awt.Font("SansSerif", 0, 13));
        tablaCategorias.setRowHeight(30);
        tablaCategorias.setShowVerticalLines(false);
        tablaCategorias.setFillsViewportHeight(true);
        btnEditar.setText("EDITAR");
        btnEditar.setBackground(new java.awt.Color(239, 246, 255));
        btnEditar.setForeground(new java.awt.Color(30, 64, 175));
        btnEditar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnEditar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnEditar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnEditar.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnEditar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnEditar.setRolloverEnabled(true);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setOpaque(false);
        btnEstado.setText("DESACTIVAR");
        btnEstado.setBackground(new java.awt.Color(239, 246, 255));
        btnEstado.setForeground(new java.awt.Color(30, 64, 175));
        btnEstado.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnEstado.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnEstado.setColorFoco(new java.awt.Color(37, 99, 235));
        btnEstado.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnEstado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnEstado.setRolloverEnabled(true);
        btnEstado.setContentAreaFilled(false);
        btnEstado.setOpaque(false);
        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.setBackground(new java.awt.Color(239, 246, 255));
        btnRefrescar.setForeground(new java.awt.Color(30, 64, 175));
        btnRefrescar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnRefrescar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnRefrescar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnRefrescar.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnRefrescar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnRefrescar.setRolloverEnabled(true);
        btnRefrescar.setContentAreaFilled(false);
        btnRefrescar.setOpaque(false);
        lblEstado.setText(" ");
        lblEstado.setForeground(new java.awt.Color(30, 41, 59));
        btnNuevo.setText("NUEVO");
        btnNuevo.setBackground(new java.awt.Color(239, 246, 255));
        btnNuevo.setForeground(new java.awt.Color(30, 64, 175));
        btnNuevo.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnNuevo.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnNuevo.setColorFoco(new java.awt.Color(37, 99, 235));
        btnNuevo.setFont(new java.awt.Font("SansSerif", 1, 13));
        btnNuevo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnNuevo.setRolloverEnabled(true);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setOpaque(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVista() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Descripción", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaCategorias.setModel(modelo);
        tablaCategorias.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaCategorias.setAutoCreateRowSorter(true);
        tablaCategorias.getTableHeader().setReorderingAllowed(false);

        btnNuevo.addActionListener(event -> limpiarFormulario());
        btnGuardar.addActionListener(event -> guardarCategoria());
        btnEditar.addActionListener(event -> cargarCategoriaSeleccionada());
        btnEstado.addActionListener(event -> cambiarEstadoSeleccionado());
        btnRefrescar.addActionListener(event -> recargarCategorias());
        btnBuscar.addActionListener(event -> recargarCategorias());
        txtBuscar.addActionListener(event -> recargarCategorias());
        tablaCategorias.getSelectionModel().addListSelectionListener(
                event -> actualizarBotonesSeleccion());
        tablaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent event) {
                if (event.getClickCount() == 2 && tablaCategorias.getSelectedRow() >= 0) {
                    cargarCategoriaSeleccionada();
                }
            }
        });
        limpiarFormulario();
    }

    public final void recargarCategorias() {
        if (cargando) {
            recargaPendiente = true;
            return;
        }
        cargando = true;
        actualizarBotonesSeleccion();
        lblEstado.setText("Cargando categorías...");
        new SwingWorker<List<CategoriaFila>, Void>() {
            @Override
            protected List<CategoriaFila> doInBackground() {
                return controller.listarCategorias(txtBuscar.getText());
            }

            @Override
            protected void done() {
                cargando = false;
                try {
                    llenarTabla(get());
                    lblEstado.setText("Categorías cargadas: " + tablaCategorias.getRowCount());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga de categorías.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar las categorías.");
                } finally {
                    actualizarBotonesSeleccion();
                    if (recargaPendiente) {
                        recargaPendiente = false;
                        recargarCategorias();
                    }
                }
            }
        }.execute();
    }

    private void llenarTabla(List<CategoriaFila> categorias) {
        DefaultTableModel modelo = (DefaultTableModel) tablaCategorias.getModel();
        tablaCategorias.clearSelection();
        modelo.setRowCount(0);
        for (CategoriaFila categoria : categorias) {
            modelo.addRow(new Object[]{
                categoria.idCategoria(), categoria.nombre(),
                categoria.descripcion() == null ? "" : categoria.descripcion(),
                categoria.activa() ? "ACTIVA" : "INACTIVA"
            });
        }
        actualizarBotonesSeleccion();
    }

    private void guardarCategoria() {
        if (cargando) {
            return;
        }
        Integer id = idCategoriaFormulario();
        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        boolean activo = chkActivo.isSelected();
        iniciarOperacion();
        new SwingWorker<ResultadoOperacion, Void>() {
            @Override
            protected ResultadoOperacion doInBackground() {
                return id == null
                        ? controller.crearCategoria(nombre, descripcion)
                        : controller.actualizarCategoria(id, nombre, descripcion, activo);
            }

            @Override
            protected void done() {
                finalizarOperacion();
                try {
                    ResultadoOperacion resultado = get();
                    if (!resultado.exitoso()) {
                        mostrarValidacion(resultado.mensaje());
                        return;
                    }
                    JOptionPane.showMessageDialog(GestionCategorias.this,
                            resultado.mensaje(), "Categorías",
                            JOptionPane.INFORMATION_MESSAGE);
                    limpiarFormulario();
                    recargarCategorias();
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió el guardado de la categoría.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible guardar la categoría.");
                }
            }
        }.execute();
    }

    private void cargarCategoriaSeleccionada() {
        Integer id = idCategoriaSeleccionado();
        if (id == null || cargando) {
            return;
        }
        iniciarOperacion();
        new SwingWorker<CategoriaEdicion, Void>() {
            @Override
            protected CategoriaEdicion doInBackground() {
                return controller.obtenerCategoriaEdicion(id).orElse(null);
            }

            @Override
            protected void done() {
                finalizarOperacion();
                try {
                    CategoriaEdicion categoria = get();
                    if (categoria == null) {
                        mostrarError("La categoría seleccionada ya no existe.");
                        recargarCategorias();
                        return;
                    }
                    txtId.setText(String.valueOf(categoria.idCategoria()));
                    txtNombre.setText(categoria.nombre());
                    txtDescripcion.setText(categoria.descripcion() == null
                            ? "" : categoria.descripcion());
                    chkActivo.setSelected(categoria.activa());
                    btnGuardar.setEnabled(true);
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga de la categoría.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar la categoría.");
                }
            }
        }.execute();
    }

    private void cambiarEstadoSeleccionado() {
        Integer id = idCategoriaSeleccionado();
        if (id == null || cargando) {
            return;
        }
        boolean activar = !categoriaSeleccionadaActiva();
        String accion = activar ? "reactivar" : "desactivar";
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Deseas " + accion + " la categoría seleccionada?",
                activar ? "Reactivar categoría" : "Desactivar categoría",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        iniciarOperacion();
        new SwingWorker<ResultadoOperacion, Void>() {
            @Override
            protected ResultadoOperacion doInBackground() {
                return controller.cambiarEstadoCategoria(id, activar);
            }

            @Override
            protected void done() {
                finalizarOperacion();
                try {
                    ResultadoOperacion resultado = get();
                    if (!resultado.exitoso()) {
                        mostrarValidacion(resultado.mensaje());
                        return;
                    }
                    limpiarFormulario();
                    recargarCategorias();
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió el cambio de estado.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cambiar el estado de la categoría.");
                }
            }
        }.execute();
    }

    private void limpiarFormulario() {
        txtId.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        chkActivo.setSelected(true);
        chkActivo.setEnabled(true);
        btnGuardar.setEnabled(!cargando);
        tablaCategorias.clearSelection();
    }

    private void iniciarOperacion() {
        cargando = true;
        btnNuevo.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEstado.setEnabled(false);
        btnRefrescar.setEnabled(false);
        btnBuscar.setEnabled(false);
    }

    private void finalizarOperacion() {
        cargando = false;
        btnNuevo.setEnabled(true);
        btnRefrescar.setEnabled(true);
        btnBuscar.setEnabled(true);
        actualizarBotonesSeleccion();
    }

    private void actualizarBotonesSeleccion() {
        boolean seleccionValida = tablaCategorias.getSelectedRow() >= 0 && !cargando;
        btnEditar.setEnabled(seleccionValida);
        btnEstado.setEnabled(seleccionValida);
        if (!seleccionValida) {
            btnEstado.setText("DESACTIVAR");
        } else {
            btnEstado.setText(categoriaSeleccionadaActiva()
                    ? "DESACTIVAR" : "REACTIVAR");
        }
    }

    private Integer idCategoriaFormulario() {
        String texto = txtId.getText().trim();
        if (texto.isEmpty()) {
            return null;
        }
        return Integer.valueOf(texto);
    }

    private Integer idCategoriaSeleccionado() {
        int fila = tablaCategorias.getSelectedRow();
        if (fila < 0) {
            return null;
        }
        int filaModelo = tablaCategorias.convertRowIndexToModel(fila);
        return (Integer) tablaCategorias.getModel().getValueAt(filaModelo, 0);
    }

    private boolean categoriaSeleccionadaActiva() {
        int filaModelo = tablaCategorias.convertRowIndexToModel(tablaCategorias.getSelectedRow());
        return "ACTIVA".equals(tablaCategorias.getModel().getValueAt(filaModelo, 3));
    }

    private void mostrarValidacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Validación",
                JOptionPane.WARNING_MESSAGE);
    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Categorías",
                JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.titanops.vista.componentes.Boton btnBuscar;
    private com.titanops.vista.componentes.Boton btnEditar;
    private com.titanops.vista.componentes.Boton btnEstado;
    private com.titanops.vista.componentes.Boton btnGuardar;
    private com.titanops.vista.componentes.Boton btnNuevo;
    private com.titanops.vista.componentes.Boton btnRefrescar;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JPanel panelListado;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JScrollPane scrollTabla;
    private com.titanops.vista.componentes.Tabla tablaCategorias;
    private com.titanops.vista.componentes.CampoTexto txtBuscar;
    private com.titanops.vista.componentes.AreaTexto txtDescripcion;
    private com.titanops.vista.componentes.CampoTexto txtId;
    private com.titanops.vista.componentes.CampoTexto txtNombre;
    // End of variables declaration//GEN-END:variables
}
