package com.titanops.vista;

import com.titanops.controlador.GestionUsuariosController;
import com.titanops.controlador.GestionUsuariosController.ResultadoCreacion;
import com.titanops.controlador.GestionUsuariosController.ResultadoOperacion;
import com.titanops.controlador.GestionUsuariosController.UsuarioEdicion;
import com.titanops.dao.RolDAO;
import com.titanops.dao.UsuarioDAO;
import com.titanops.modelo.Rol;
import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.ExecutionException;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.border.TitledBorder;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author aleyt
 */
public class GESTIONUS1 extends javax.swing.JInternalFrame {

    private javax.swing.JDesktopPane desktop;
    private final GestionUsuariosController controller;
    private final Integer idUsuarioSesion;
    private final Integer idUsuarioEdicion;
    private boolean operacionEnCurso;

    public GESTIONUS1(javax.swing.JDesktopPane desktop) {
        this(desktop, null);
    }

    public GESTIONUS1(javax.swing.JDesktopPane desktop, Integer idUsuarioSesion) {
        this(desktop, idUsuarioSesion, null,
                new GestionUsuariosController(new UsuarioDAO(), new RolDAO()));
    }

    public GESTIONUS1(javax.swing.JDesktopPane desktop, Integer idUsuarioSesion,
                      int idUsuarioEdicion) {
        this(desktop, idUsuarioSesion, idUsuarioEdicion,
                new GestionUsuariosController(new UsuarioDAO(), new RolDAO()));
    }

    GESTIONUS1(javax.swing.JDesktopPane desktop, Integer idUsuarioSesion,
               Integer idUsuarioEdicion, GestionUsuariosController controller) {
        initComponents();
        this.desktop = desktop;
        this.idUsuarioSesion = idUsuarioSesion;
        this.idUsuarioEdicion = idUsuarioEdicion;
        this.controller = controller;
        configurarFormulario();

        cargarRoles();
    }

    public GESTIONUS1() {
        this((javax.swing.JDesktopPane) null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel00 = new javax.swing.JLabel();
        jTextField1 = new com.titanops.vista.componentes.CampoClave();
        jTextField2 = new com.titanops.vista.componentes.CampoTexto();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new com.titanops.vista.componentes.CampoTexto();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new com.titanops.vista.componentes.Selector<>();
        GUARDARUS = new com.titanops.vista.componentes.Boton();
        GUARDARUS1 = new com.titanops.vista.componentes.Boton();
        GUARDARUS2 = new com.titanops.vista.componentes.Boton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);



        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("CREAR USUARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/USUARIO.png"))); // NOI18N

        jLabel00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/CANDADO.png"))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/CORREO.png"))); // NOI18N

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ROLES.png"))); // NOI18N

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setBorder(null);

        GUARDARUS.setBackground(new java.awt.Color(37, 99, 235));
        GUARDARUS.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        GUARDARUS.setForeground(new java.awt.Color(255, 255, 255));
        GUARDARUS.setText("GUARDAR");
        GUARDARUS.setBorder(null);

        GUARDARUS1.setBackground(new java.awt.Color(37, 99, 235));
        GUARDARUS1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        GUARDARUS1.setForeground(new java.awt.Color(255, 255, 255));
        GUARDARUS1.setText("SALIR");
        GUARDARUS1.setBorder(null);

        GUARDARUS2.setBackground(new java.awt.Color(37, 99, 235));
        GUARDARUS2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        GUARDARUS2.setForeground(new java.awt.Color(255, 255, 255));
        GUARDARUS2.setText("GESTIONAR");
        GUARDARUS2.setBorder(null);
        GUARDARUS2.addActionListener(this::GUARDARUS2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel00, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(GUARDARUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GUARDARUS1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GUARDARUS2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel00)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUARDARUS)
                    .addComponent(GUARDARUS1)
                    .addComponent(GUARDARUS2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );


        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        jPanel1.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.setBackground(new java.awt.Color(239, 246, 255));
        jPanel2.setForeground(new java.awt.Color(30, 41, 59));
        jPanel2.setBackground(new java.awt.Color(30, 64, 175));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(30, 41, 59));
        jLabel00.setForeground(new java.awt.Color(30, 41, 59));
        jLabel2.setForeground(new java.awt.Color(30, 41, 59));
        jLabel3.setForeground(new java.awt.Color(30, 41, 59));


        jPanel1.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.setBackground(new java.awt.Color(239, 246, 255));
        jPanel2.setForeground(new java.awt.Color(30, 41, 59));
        jPanel2.setBackground(new java.awt.Color(30, 64, 175));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));
        jLabel1.setText("CREAR USUARIO");
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(30, 41, 59));
        jLabel00.setForeground(new java.awt.Color(30, 41, 59));
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(30, 41, 59));
        jTextField1.setColorFoco(new java.awt.Color(37, 99, 235));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 13));
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField1.setSelectionColor(new java.awt.Color(191, 219, 254));
        jTextField1.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        jTextField1.setCaretColor(new java.awt.Color(37, 99, 235));
        jTextField1.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        jTextField1.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(30, 41, 59));
        jTextField2.setColorFoco(new java.awt.Color(37, 99, 235));
        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 13));
        jTextField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField2.setSelectionColor(new java.awt.Color(191, 219, 254));
        jTextField2.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        jTextField2.setCaretColor(new java.awt.Color(37, 99, 235));
        jTextField2.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        jTextField2.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        jTextField2.setPlaceholder("Nombre de usuario para iniciar sesión");
        jLabel2.setForeground(new java.awt.Color(30, 41, 59));
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(30, 41, 59));
        jTextField3.setColorFoco(new java.awt.Color(37, 99, 235));
        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 13));
        jTextField3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        jTextField3.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField3.setSelectionColor(new java.awt.Color(191, 219, 254));
        jTextField3.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        jTextField3.setCaretColor(new java.awt.Color(37, 99, 235));
        jTextField3.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        jTextField3.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        jTextField3.setPlaceholder("Nombre completo de la persona");
        jLabel3.setForeground(new java.awt.Color(30, 41, 59));
        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(30, 41, 59));
        jComboBox1.setColorFoco(new java.awt.Color(37, 99, 235));
        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 13));
        jComboBox1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        jComboBox1.setPreferredSize(new java.awt.Dimension(180, 30));
        GUARDARUS.setText("GUARDAR");
        GUARDARUS.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS.setFont(new java.awt.Font("SansSerif", 1, 13));
        GUARDARUS.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS.setRolloverEnabled(true);
        GUARDARUS.setContentAreaFilled(false);
        GUARDARUS.setOpaque(false);
        GUARDARUS1.setText("SALIR");
        GUARDARUS1.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS1.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS1.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS1.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS1.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS1.setFont(new java.awt.Font("SansSerif", 1, 13));
        GUARDARUS1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS1.setRolloverEnabled(true);
        GUARDARUS1.setContentAreaFilled(false);
        GUARDARUS1.setOpaque(false);
        GUARDARUS2.setText("GESTIONAR");
        GUARDARUS2.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS2.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS2.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS2.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS2.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS2.setFont(new java.awt.Font("SansSerif", 1, 13));
        GUARDARUS2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS2.setRolloverEnabled(true);
        GUARDARUS2.setContentAreaFilled(false);
        GUARDARUS2.setOpaque(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarFormulario() {
        boolean editando = idUsuarioEdicion != null;
        jLabel1.setText(editando ? "EDITAR USUARIO" : "CREAR USUARIO");
        GUARDARUS.setText(editando ? "ACTUALIZAR" : "GUARDAR");

        jTextField2.setToolTipText("Nombre de usuario para iniciar sesión");
        jTextField3.setToolTipText("Nombre completo de la persona");
        jTextField1.setToolTipText(editando
                ? "Déjala vacía para conservar la contraseña actual"
                : "Mínimo 8 caracteres");
        GUARDARUS.setToolTipText(editando ? "Actualizar usuario" : "Crear usuario");
        GUARDARUS.addActionListener(event -> guardarUsuario());
        GUARDARUS1.addActionListener(event -> dispose());
        getRootPane().setDefaultButton(GUARDARUS);
    }

    private void cargarRoles() {
        cambiarEstadoFormulario(true);
        new SwingWorker<List<Rol>, Void>() {
            @Override
            protected List<Rol> doInBackground() {
                return controller.listarRoles();
            }

            @Override
            protected void done() {
                try {
                    DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
                    for (Rol rol : get()) {
                        modelo.addElement(rol.getNombreRol());
                    }
                    jComboBox1.setModel(modelo);
                    cambiarEstadoFormulario(false);
                    GUARDARUS.setEnabled(modelo.getSize() > 0);
                    if (modelo.getSize() == 0) {
                        mostrarError("No se encontraron roles disponibles.");
                    } else if (idUsuarioEdicion != null) {
                        cargarUsuarioEdicion();
                    }
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    cambiarEstadoFormulario(false);
                    GUARDARUS.setEnabled(false);
                    mostrarError("Se interrumpió la carga de roles.");
                } catch (ExecutionException exception) {
                    cambiarEstadoFormulario(false);
                    GUARDARUS.setEnabled(false);
                    mostrarError("No fue posible cargar los roles.");
                }
            }
        }.execute();
    }

    private void cargarUsuarioEdicion() {
        cambiarEstadoFormulario(true);
        new SwingWorker<Optional<UsuarioEdicion>, Void>() {
            @Override
            protected Optional<UsuarioEdicion> doInBackground() {
                return controller.obtenerUsuarioEdicion(idUsuarioEdicion);
            }

            @Override
            protected void done() {
                cambiarEstadoFormulario(false);
                try {
                    Optional<UsuarioEdicion> usuario = get();
                    if (usuario.isEmpty()) {
                        mostrarError("El usuario seleccionado ya no está disponible.");
                        dispose();
                        return;
                    }
                    jTextField3.setText(usuario.get().nombreCompleto());
                    jTextField2.setText(usuario.get().username());
                    jTextField1.setText("");
                    jComboBox1.setSelectedItem(usuario.get().rol());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga del usuario.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar el usuario.");
                }
            }
        }.execute();
    }

    private void guardarUsuario() {
        if (operacionEnCurso) {
            return;
        }

        String nombreCompleto = jTextField3.getText();
        String username = jTextField2.getText();
        String nombreRol = (String) jComboBox1.getSelectedItem();
        char[] clave = jTextField1.getPassword();
        cambiarEstadoFormulario(true);

        new SwingWorker<ResultadoOperacion, Void>() {
            @Override
            protected ResultadoOperacion doInBackground() {
                try {
                    if (idUsuarioEdicion != null) {
                        return controller.actualizarUsuario(
                                idUsuarioEdicion, nombreCompleto, username, clave,
                                nombreRol, idUsuarioSesion);
                    }
                    ResultadoCreacion resultado = controller.crearUsuario(
                            nombreCompleto, username, clave, nombreRol);
                    return new ResultadoOperacion(resultado.exitoso(), resultado.mensaje());
                } finally {
                    Arrays.fill(clave, '\0');
                }
            }

            @Override
            protected void done() {
                cambiarEstadoFormulario(false);
                try {
                    ResultadoOperacion resultado = get();
                    if (!resultado.exitoso()) {
                        JOptionPane.showMessageDialog(GESTIONUS1.this, resultado.mensaje(),
                                "Validación", JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    if (idUsuarioEdicion == null) {
                        limpiarFormulario();
                    } else {
                        jTextField1.setText("");
                    }
                    refrescarListadosAbiertos();
                    JOptionPane.showMessageDialog(GESTIONUS1.this, resultado.mensaje(),
                            idUsuarioEdicion == null ? "Usuario creado" : "Usuario actualizado",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la creación del usuario.");
                } catch (ExecutionException exception) {
                    mostrarError("Ocurrió un error al crear el usuario.");
                }
            }
        }.execute();
    }

    private void cambiarEstadoFormulario(boolean ocupado) {
        operacionEnCurso = ocupado;
        jTextField1.setEnabled(!ocupado);
        jTextField2.setEnabled(!ocupado);
        jTextField3.setEnabled(!ocupado);
        jComboBox1.setEnabled(!ocupado);
        GUARDARUS.setEnabled(!ocupado);
    }

    private void limpiarFormulario() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField2.requestFocusInWindow();
    }

    private void refrescarListadosAbiertos() {
        javax.swing.JDesktopPane panel = obtenerDesktop();
        if (panel == null) {
            return;
        }
        for (JInternalFrame frame : panel.getAllFrames()) {
            if (frame instanceof GESTIONUS gestionUsuarios) {
                gestionUsuarios.recargarUsuarios();
            }
        }
    }

    private javax.swing.JDesktopPane obtenerDesktop() {
        return desktop != null ? desktop : getDesktopPane();
    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Gestión de usuarios",
                JOptionPane.ERROR_MESSAGE);
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        guardarUsuario();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void GUARDARUS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARUS2ActionPerformed
        javax.swing.JDesktopPane panel = obtenerDesktop();
        if (panel == null) {
            mostrarError("No se encontró el escritorio principal.");
            return;
        }

        for (JInternalFrame frame : panel.getAllFrames()) {
            if (frame instanceof GESTIONUS gestionUsuarios) {
                gestionUsuarios.recargarUsuarios();
                gestionUsuarios.setVisible(true);
                gestionUsuarios.toFront();
                return;
            }
        }

        GESTIONUS panta = new GESTIONUS(idUsuarioSesion);
        panel.add(panta);
        panta.setSize(900, 550);
        panta.setLocation(20, 20);
        panta.setVisible(true);
        panta.toFront();
    }//GEN-LAST:event_GUARDARUS2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.titanops.vista.componentes.Boton GUARDARUS;
    private com.titanops.vista.componentes.Boton GUARDARUS1;
    private com.titanops.vista.componentes.Boton GUARDARUS2;
    private com.titanops.vista.componentes.Selector<String> jComboBox1;
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.titanops.vista.componentes.CampoClave jTextField1;
    private com.titanops.vista.componentes.CampoTexto jTextField2;
    private com.titanops.vista.componentes.CampoTexto jTextField3;
    // End of variables declaration//GEN-END:variables
}
