/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.titanops.vista;

/**
 *
 * @author Natha
 */
public class Gestion_de_operadores extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gestion_de_operadores
     */
    public Gestion_de_operadores() {
        initComponents();
         panelVista.setLayout(new java.awt.BorderLayout());
         mostrarPanel(new Operario());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelVista = new javax.swing.JPanel();
        btn_operario = new com.titanops.vista.componentes.Boton();
        btn_operario1 = new com.titanops.vista.componentes.Boton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(960, 680));



        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32)); // NOI18N
        jLabel2.setText("GESTIÓN DE OPERADORES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelVistaLayout = new javax.swing.GroupLayout(panelVista);
        panelVista.setLayout(panelVistaLayout);
        panelVistaLayout.setHorizontalGroup(
            panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelVistaLayout.setVerticalGroup(
            panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        btn_operario.setBackground(new java.awt.Color(37, 99, 235));
        btn_operario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btn_operario.setForeground(new java.awt.Color(255, 255, 255));
        btn_operario.setText("OPERADORES");
        btn_operario.setBorder(null);
        btn_operario.addActionListener(this::btn_operarioActionPerformed);

        btn_operario1.setBackground(new java.awt.Color(37, 99, 235));
        btn_operario1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btn_operario1.setForeground(new java.awt.Color(255, 255, 255));
        btn_operario1.setText("CERTIFICACIONES");
        btn_operario1.setBorder(null);
        btn_operario1.addActionListener(this::btn_operario1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_operario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_operario1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_operario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_operario1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );


        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        jPanel1.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.setBackground(new java.awt.Color(239, 246, 255));
        jPanel3.setForeground(new java.awt.Color(30, 41, 59));
        jPanel3.setBackground(new java.awt.Color(30, 64, 175));
        panelVista.setForeground(new java.awt.Color(30, 41, 59));
        panelVista.setBackground(new java.awt.Color(248, 250, 252));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setBackground(new java.awt.Color(239, 246, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));


        jPanel1.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.setBackground(new java.awt.Color(239, 246, 255));
        jPanel3.setForeground(new java.awt.Color(30, 41, 59));
        jPanel3.setBackground(new java.awt.Color(30, 64, 175));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 32));
        jLabel2.setText("GESTIÓN DE OPERADORES");
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        panelVista.setForeground(new java.awt.Color(30, 41, 59));
        panelVista.setBackground(new java.awt.Color(248, 250, 252));
        btn_operario.setText("OPERADORES");
        btn_operario.setBackground(new java.awt.Color(239, 246, 255));
        btn_operario.setForeground(new java.awt.Color(30, 64, 175));
        btn_operario.setFondoActivo(new java.awt.Color(37, 99, 235));
        btn_operario.setTextoActivo(new java.awt.Color(255, 255, 255));
        btn_operario.setColorFoco(new java.awt.Color(37, 99, 235));
        btn_operario.setFont(new java.awt.Font("SansSerif", 1, 13));
        btn_operario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btn_operario.setRolloverEnabled(true);
        btn_operario.setContentAreaFilled(false);
        btn_operario.setOpaque(false);
        btn_operario1.setText("CERTIFICACIONES");
        btn_operario1.setBackground(new java.awt.Color(239, 246, 255));
        btn_operario1.setForeground(new java.awt.Color(30, 64, 175));
        btn_operario1.setFondoActivo(new java.awt.Color(37, 99, 235));
        btn_operario1.setTextoActivo(new java.awt.Color(255, 255, 255));
        btn_operario1.setColorFoco(new java.awt.Color(37, 99, 235));
        btn_operario1.setFont(new java.awt.Font("SansSerif", 1, 13));
        btn_operario1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252), 1), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btn_operario1.setRolloverEnabled(true);
        btn_operario1.setContentAreaFilled(false);
        btn_operario1.setOpaque(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_operarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operarioActionPerformed
       mostrarPanel(new Operario());  
    }//GEN-LAST:event_btn_operarioActionPerformed

    private void btn_operario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operario1ActionPerformed
        mostrarPanel(new Certifiaciones());
    }//GEN-LAST:event_btn_operario1ActionPerformed

    
      private void mostrarPanel(javax.swing.JPanel panel) {

    panelVista.removeAll();

    
    // El JPanel ocupa exactamente TODO panelVista
    panelVista.add(panel, java.awt.BorderLayout.CENTER);

    panelVista.revalidate();
    panelVista.repaint();
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.titanops.vista.componentes.Boton btn_operario;
    private com.titanops.vista.componentes.Boton btn_operario1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelVista;
    // End of variables declaration//GEN-END:variables
}
