package com.titanops.vista;

import com.titanops.controlador.GestionMaquinariaController;
import com.titanops.controlador.GestionMaquinariaController.CategoriaOpcion;
import com.titanops.controlador.GestionMaquinariaController.MaquinariaEdicion;
import com.titanops.controlador.GestionMaquinariaController.MaquinariaFila;
import com.titanops.controlador.GestionMaquinariaController.ResultadoCreacion;
import com.titanops.controlador.GestionMaquinariaController.ResultadoCategoria;
import com.titanops.controlador.GestionMaquinariaController.ResultadoOperacion;
import com.titanops.dao.CategoriaMaquinariaDAO;
import com.titanops.dao.MaquinariaDAO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.ExecutionException;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author aleyt
 */
public class MAQUINARIAGESTION extends javax.swing.JInternalFrame {

    private static final DateTimeFormatter FORMATO_FECHA =
            DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    private javax.swing.JDesktopPane desktop;
    private final GestionMaquinariaController controller;
    private List<CategoriaOpcion> categorias = List.of();
    private boolean cargando;
    private boolean recargaPendiente;

    public MAQUINARIAGESTION(javax.swing.JDesktopPane desktop) {
        this(desktop, new GestionMaquinariaController(
                new MaquinariaDAO(), new CategoriaMaquinariaDAO()));
    }

    public MAQUINARIAGESTION() {
        this(null);
    }

    MAQUINARIAGESTION(javax.swing.JDesktopPane desktop,
                      GestionMaquinariaController controller) {
        initComponents();
        this.desktop = desktop;
        this.controller = controller;
        configurarVista();

        cargarDatosIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        panelCreacion = new javax.swing.JPanel();
        lblFormulario = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        lblTxtCodigo = new javax.swing.JLabel();
        txtCodigo = new com.titanops.vista.componentes.CampoTexto();
        lblCmbCategoria = new javax.swing.JLabel();
        cmbCategoria = new com.titanops.vista.componentes.Selector();
        lblTxtMarca = new javax.swing.JLabel();
        txtMarca = new com.titanops.vista.componentes.CampoTexto();
        lblTxtModelo = new javax.swing.JLabel();
        txtModelo = new com.titanops.vista.componentes.CampoTexto();
        lblTxtTonelaje = new javax.swing.JLabel();
        txtTonelaje = new com.titanops.vista.componentes.CampoTexto();
        lblTxtHorasUso = new javax.swing.JLabel();
        txtHorasUso = new com.titanops.vista.componentes.CampoTexto();
        lblCmbEstado = new javax.swing.JLabel();
        cmbEstado = new com.titanops.vista.componentes.Selector();
        panelAccionesCreacion = new javax.swing.JPanel();
        btnNuevaCategoria = new com.titanops.vista.componentes.Boton();
        btnLimpiar = new com.titanops.vista.componentes.Boton();
        btnGuardar = new com.titanops.vista.componentes.Boton();
        panelListado = new javax.swing.JPanel();
        panelFiltros = new javax.swing.JPanel();
        lblTxtBuscar = new javax.swing.JLabel();
        txtBuscar = new com.titanops.vista.componentes.CampoTexto();
        lblCmbFiltroEstado = new javax.swing.JLabel();
        cmbFiltroEstado = new com.titanops.vista.componentes.Selector();
        btnBuscar = new com.titanops.vista.componentes.Boton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new com.titanops.vista.componentes.Tabla();
        panelAcciones = new javax.swing.JPanel();
        btnEditar = new com.titanops.vista.componentes.Boton();
        btnEstadoRegistro = new com.titanops.vista.componentes.Boton();
        lblEstadoCarga = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 246, 255));
        setClosable(true);
        setForeground(new java.awt.Color(30, 41, 59));
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión de maquinaria");
        setPreferredSize(new java.awt.Dimension(1120, 700));
        getContentPane().setLayout(new java.awt.BorderLayout(12, 12));

        jPanel1.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.setBackground(new java.awt.Color(239, 246, 255));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 12));

        panelCabecera.setForeground(new java.awt.Color(30, 41, 59));
        panelCabecera.setBackground(new java.awt.Color(30, 64, 175));
        panelCabecera.setLayout(new java.awt.BorderLayout());

        lblTitulo.setText("GESTIÓN DE MAQUINARIA");
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCabecera.add(lblTitulo, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelCabecera, java.awt.BorderLayout.NORTH);

        panelCentro.setForeground(new java.awt.Color(30, 41, 59));
        panelCentro.setBackground(new java.awt.Color(248, 250, 252));
        panelCentro.setLayout(new java.awt.BorderLayout(16, 0));

        panelCreacion.setPreferredSize(new java.awt.Dimension(360, 500));
        panelCreacion.setForeground(new java.awt.Color(30, 41, 59));
        panelCreacion.setBackground(new java.awt.Color(248, 250, 252));
        panelCreacion.setLayout(new java.awt.BorderLayout(0, 10));

        lblFormulario.setText("DATOS DE LA MAQUINARIA");
        lblFormulario.setForeground(new java.awt.Color(30, 41, 59));
        panelCreacion.add(lblFormulario, java.awt.BorderLayout.NORTH);

        panelDatos.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.setBackground(new java.awt.Color(248, 250, 252));
        panelDatos.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        lblTxtCodigo.setText("Código");
        lblTxtCodigo.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxtCodigo);

        txtCodigo.setForeground(new java.awt.Color(30, 41, 59));
        txtCodigo.setColorFoco(new java.awt.Color(37, 99, 235));
        txtCodigo.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtCodigo.setPreferredSize(new java.awt.Dimension(200, 40));
        txtCodigo.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtCodigo.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtCodigo.setCaretColor(new java.awt.Color(37, 99, 235));
        txtCodigo.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtCodigo.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txtCodigo.setPlaceholder("Código único de inventario");
        panelDatos.add(txtCodigo);

        lblCmbCategoria.setText("Categoría");
        lblCmbCategoria.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblCmbCategoria);

        cmbCategoria.setForeground(new java.awt.Color(30, 41, 59));
        cmbCategoria.setColorFoco(new java.awt.Color(37, 99, 235));
        cmbCategoria.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        cmbCategoria.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        cmbCategoria.setPreferredSize(new java.awt.Dimension(180, 30));
        panelDatos.add(cmbCategoria);

        lblTxtMarca.setText("Marca");
        lblTxtMarca.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxtMarca);

        txtMarca.setForeground(new java.awt.Color(30, 41, 59));
        txtMarca.setColorFoco(new java.awt.Color(37, 99, 235));
        txtMarca.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtMarca.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtMarca.setPreferredSize(new java.awt.Dimension(200, 40));
        txtMarca.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtMarca.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtMarca.setCaretColor(new java.awt.Color(37, 99, 235));
        txtMarca.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtMarca.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        panelDatos.add(txtMarca);

        lblTxtModelo.setText("Modelo");
        lblTxtModelo.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxtModelo);

        txtModelo.setForeground(new java.awt.Color(30, 41, 59));
        txtModelo.setColorFoco(new java.awt.Color(37, 99, 235));
        txtModelo.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtModelo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtModelo.setPreferredSize(new java.awt.Dimension(200, 40));
        txtModelo.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtModelo.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtModelo.setCaretColor(new java.awt.Color(37, 99, 235));
        txtModelo.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtModelo.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        panelDatos.add(txtModelo);

        lblTxtTonelaje.setText("Tonelaje");
        lblTxtTonelaje.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxtTonelaje);

        txtTonelaje.setForeground(new java.awt.Color(30, 41, 59));
        txtTonelaje.setColorFoco(new java.awt.Color(37, 99, 235));
        txtTonelaje.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtTonelaje.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtTonelaje.setPreferredSize(new java.awt.Dimension(200, 40));
        txtTonelaje.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtTonelaje.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtTonelaje.setCaretColor(new java.awt.Color(37, 99, 235));
        txtTonelaje.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtTonelaje.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txtTonelaje.setPlaceholder("Hasta 8 enteros y 2 decimales");
        panelDatos.add(txtTonelaje);

        lblTxtHorasUso.setText("Horas de uso");
        lblTxtHorasUso.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxtHorasUso);

        txtHorasUso.setForeground(new java.awt.Color(30, 41, 59));
        txtHorasUso.setColorFoco(new java.awt.Color(37, 99, 235));
        txtHorasUso.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtHorasUso.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtHorasUso.setPreferredSize(new java.awt.Dimension(200, 40));
        txtHorasUso.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtHorasUso.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtHorasUso.setCaretColor(new java.awt.Color(37, 99, 235));
        txtHorasUso.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtHorasUso.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txtHorasUso.setPlaceholder("Hasta 8 enteros y 2 decimales");
        panelDatos.add(txtHorasUso);

        lblCmbEstado.setText("Estado");
        lblCmbEstado.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblCmbEstado);

        cmbEstado.setForeground(new java.awt.Color(30, 41, 59));
        cmbEstado.setColorFoco(new java.awt.Color(37, 99, 235));
        cmbEstado.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        cmbEstado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        cmbEstado.setPreferredSize(new java.awt.Dimension(180, 30));
        panelDatos.add(cmbEstado);

        panelCreacion.add(panelDatos, java.awt.BorderLayout.CENTER);

        panelAccionesCreacion.setForeground(new java.awt.Color(30, 41, 59));
        panelAccionesCreacion.setBackground(new java.awt.Color(248, 250, 252));
        panelAccionesCreacion.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        btnNuevaCategoria.setText("NUEVA CATEGORÍA");
        btnNuevaCategoria.setBackground(new java.awt.Color(239, 246, 255));
        btnNuevaCategoria.setForeground(new java.awt.Color(30, 64, 175));
        btnNuevaCategoria.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnNuevaCategoria.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnNuevaCategoria.setColorFoco(new java.awt.Color(37, 99, 235));
        btnNuevaCategoria.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnNuevaCategoria.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnNuevaCategoria.setContentAreaFilled(false);
        panelAccionesCreacion.add(btnNuevaCategoria);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBackground(new java.awt.Color(239, 246, 255));
        btnLimpiar.setForeground(new java.awt.Color(30, 64, 175));
        btnLimpiar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnLimpiar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnLimpiar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnLimpiar.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnLimpiar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnLimpiar.setContentAreaFilled(false);
        panelAccionesCreacion.add(btnLimpiar);

        btnGuardar.setText("GUARDAR");
        btnGuardar.setBackground(new java.awt.Color(239, 246, 255));
        btnGuardar.setForeground(new java.awt.Color(30, 64, 175));
        btnGuardar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnGuardar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnGuardar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnGuardar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnGuardar.setContentAreaFilled(false);
        panelAccionesCreacion.add(btnGuardar);

        panelCreacion.add(panelAccionesCreacion, java.awt.BorderLayout.SOUTH);

        panelCentro.add(panelCreacion, java.awt.BorderLayout.WEST);

        panelListado.setForeground(new java.awt.Color(30, 41, 59));
        panelListado.setBackground(new java.awt.Color(248, 250, 252));
        panelListado.setLayout(new java.awt.BorderLayout(0, 10));

        panelFiltros.setForeground(new java.awt.Color(30, 41, 59));
        panelFiltros.setBackground(new java.awt.Color(248, 250, 252));
        panelFiltros.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 6));

        lblTxtBuscar.setText("Buscar:");
        lblTxtBuscar.setForeground(new java.awt.Color(30, 41, 59));
        panelFiltros.add(lblTxtBuscar);

        txtBuscar.setForeground(new java.awt.Color(30, 41, 59));
        txtBuscar.setColorFoco(new java.awt.Color(37, 99, 235));
        txtBuscar.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtBuscar.setPreferredSize(new java.awt.Dimension(200, 40));
        txtBuscar.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtBuscar.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtBuscar.setCaretColor(new java.awt.Color(37, 99, 235));
        txtBuscar.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtBuscar.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txtBuscar.setPlaceholder("Buscar por código, categoría, marca o modelo");
        panelFiltros.add(txtBuscar);

        lblCmbFiltroEstado.setText("Estado:");
        lblCmbFiltroEstado.setForeground(new java.awt.Color(30, 41, 59));
        panelFiltros.add(lblCmbFiltroEstado);

        cmbFiltroEstado.setForeground(new java.awt.Color(30, 41, 59));
        cmbFiltroEstado.setColorFoco(new java.awt.Color(37, 99, 235));
        cmbFiltroEstado.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        cmbFiltroEstado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        cmbFiltroEstado.setPreferredSize(new java.awt.Dimension(180, 30));
        panelFiltros.add(cmbFiltroEstado);

        btnBuscar.setText("BUSCAR");
        btnBuscar.setBackground(new java.awt.Color(239, 246, 255));
        btnBuscar.setForeground(new java.awt.Color(30, 64, 175));
        btnBuscar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnBuscar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnBuscar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnBuscar.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnBuscar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnBuscar.setContentAreaFilled(false);
        panelFiltros.add(btnBuscar);

        panelListado.add(panelFiltros, java.awt.BorderLayout.NORTH);

        jScrollPane1.setForeground(new java.awt.Color(30, 41, 59));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)));
        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setForeground(new java.awt.Color(30, 41, 59));
        jTable1.setGridColor(new java.awt.Color(125, 211, 252));
        jTable1.setSelectionBackground(new java.awt.Color(219, 234, 254));
        jTable1.setSelectionForeground(new java.awt.Color(30, 64, 175));
        jTable1.setFondoCabecera(new java.awt.Color(224, 242, 254));
        jTable1.setTextoCabecera(new java.awt.Color(30, 64, 175));
        jTable1.setBordeCabecera(new java.awt.Color(125, 211, 252));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)));
        jTable1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jTable1.setRowHeight(30);
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        panelListado.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelAcciones.setForeground(new java.awt.Color(30, 41, 59));
        panelAcciones.setBackground(new java.awt.Color(248, 250, 252));
        panelAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 5));

        btnEditar.setText("EDITAR");
        btnEditar.setBackground(new java.awt.Color(239, 246, 255));
        btnEditar.setForeground(new java.awt.Color(30, 64, 175));
        btnEditar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnEditar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnEditar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnEditar.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnEditar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnEditar.setContentAreaFilled(false);
        panelAcciones.add(btnEditar);

        btnEstadoRegistro.setText("DESACTIVAR");
        btnEstadoRegistro.setBackground(new java.awt.Color(239, 246, 255));
        btnEstadoRegistro.setForeground(new java.awt.Color(30, 64, 175));
        btnEstadoRegistro.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnEstadoRegistro.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnEstadoRegistro.setColorFoco(new java.awt.Color(37, 99, 235));
        btnEstadoRegistro.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnEstadoRegistro.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnEstadoRegistro.setContentAreaFilled(false);
        panelAcciones.add(btnEstadoRegistro);

        panelListado.add(panelAcciones, java.awt.BorderLayout.SOUTH);

        panelCentro.add(panelListado, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelCentro, java.awt.BorderLayout.CENTER);

        lblEstadoCarga.setText(" ");
        lblEstadoCarga.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.add(lblEstadoCarga, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void configurarVista() {
        cmbEstado.setModel(new DefaultComboBoxModel<>(GestionMaquinariaController.ESTADOS_OPERATIVOS.toArray(String[]::new)));
        DefaultComboBoxModel<String> estados = new DefaultComboBoxModel<>();
        estados.addElement("TODOS");
        for (String estado : GestionMaquinariaController.ESTADOS_OPERATIVOS) estados.addElement(estado);
        cmbFiltroEstado.setModel(estados);
        jTable1.setModel(new DefaultTableModel(new Object[]{"ID", "Código", "Categoría", "Marca", "Modelo", "Tonelaje", "Horas", "Estado operativo", "Estado del registro", "Fecha de registro"}, 0) {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        });
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        txtCodigo.setToolTipText("Código único de inventario");
        txtTonelaje.setToolTipText("Hasta 8 enteros y 2 decimales");
        txtHorasUso.setToolTipText("Hasta 8 enteros y 2 decimales");
        txtBuscar.setToolTipText("Buscar por código, categoría, marca o modelo");
        btnGuardar.addActionListener(event -> crearMaquinaria());
        btnNuevaCategoria.addActionListener(event -> crearCategoria());
        btnLimpiar.addActionListener(event -> limpiarFormulario());
        btnBuscar.addActionListener(event -> recargarMaquinaria());
        btnEditar.addActionListener(event -> cargarEdicionSeleccionada());
        btnEstadoRegistro.addActionListener(event -> cambiarEstadoSeleccionado());
        txtBuscar.addActionListener(event -> recargarMaquinaria());
        cmbFiltroEstado.addActionListener(event -> {
            if (!cargando) {
                recargarMaquinaria();
            }
        });
        jTable1.getSelectionModel().addListSelectionListener(
                event -> actualizarBotonesSeleccion());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent event) {
                if (event.getClickCount() == 2 && jTable1.getSelectedRow() >= 0) {
                    cargarEdicionSeleccionada();
                }
            }
        });

        setMinimumSize(new Dimension(920, 620));
        setSize(1120, 700);
        actualizarBotonesSeleccion();
    }

    private void crearCategoria() {
        if (cargando) {
            return;
        }
        JTextField nombre = new JTextField(24);
        JTextField descripcion = new JTextField(24);
        JPanel formulario = new JPanel(new GridBagLayout());
        formulario.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        agregarCampo(formulario, 0, "Nombre", nombre);
        agregarCampo(formulario, 1, "Descripción (opcional)", descripcion);

        int respuesta = JOptionPane.showConfirmDialog(this, formulario,
                "Nueva categoría de maquinaria", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        if (respuesta != JOptionPane.OK_OPTION) {
            return;
        }

        String nombreCategoria = nombre.getText();
        String descripcionCategoria = descripcion.getText();
        iniciarOperacion();
        new SwingWorker<ResultadoCategoriaConListado, Void>() {
            @Override
            protected ResultadoCategoriaConListado doInBackground() {
                ResultadoCategoria resultado = controller.crearCategoria(
                        nombreCategoria, descripcionCategoria);
                List<CategoriaOpcion> listado = resultado.exitoso()
                        ? controller.listarCategorias() : List.of();
                return new ResultadoCategoriaConListado(resultado, listado);
            }

            @Override
            protected void done() {
                try {
                    ResultadoCategoriaConListado datos = get();
                    if (!datos.resultado().exitoso()) {
                        mostrarValidacion(datos.resultado().mensaje());
                        return;
                    }
                    categorias = datos.categorias();
                    llenarCategorias();
                    seleccionarCategoria(cmbCategoria,
                            datos.resultado().idCategoria());
                    JOptionPane.showMessageDialog(MAQUINARIAGESTION.this,
                            datos.resultado().mensaje(), "Categoría de maquinaria",
                            JOptionPane.INFORMATION_MESSAGE);
                    lblEstadoCarga.setText("Categoría disponible para registrar maquinaria.");
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la creación de la categoría.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible crear la categoría.");
                } finally {
                    terminarOperacion();
                }
            }
        }.execute();
    }

    private void cargarDatosIniciales() {
        if (cargando) {
            return;
        }
        cargando = true;
        cambiarEstadoInterfaz(true);
        lblEstadoCarga.setText("Cargando categorías y maquinaria...");
        new SwingWorker<DatosIniciales, Void>() {
            @Override
            protected DatosIniciales doInBackground() {
                return new DatosIniciales(
                        controller.listarCategorias(), controller.listarMaquinaria());
            }

            @Override
            protected void done() {
                cargando = false;
                try {
                    DatosIniciales datos = get();
                    categorias = datos.categorias();
                    llenarCategorias();
                    llenarTabla(datos.maquinaria());
                    lblEstadoCarga.setText(categorias.stream().anyMatch(CategoriaOpcion::activa)
                            ? "Datos cargados correctamente."
                            : "No hay categorías activas; crea una categoría en la base antes de registrar maquinaria.");
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga inicial.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar las categorías y la maquinaria.");
                } finally {
                    cambiarEstadoInterfaz(false);
                }
            }
        }.execute();
    }

    private void llenarCategorias() {
        DefaultComboBoxModel<CategoriaOpcion> modelo = new DefaultComboBoxModel<>();
        for (CategoriaOpcion categoria : categorias) {
            if (categoria.activa()) {
                modelo.addElement(categoria);
            }
        }
        cmbCategoria.setModel(modelo);
    }

    public final void recargarMaquinaria() {
        if (cargando) {
            recargaPendiente = true;
            return;
        }
        cargando = true;
        cambiarEstadoInterfaz(true);
        lblEstadoCarga.setText("Cargando maquinaria...");
        String filtro = txtBuscar.getText();
        String estado = (String) cmbFiltroEstado.getSelectedItem();
        new SwingWorker<List<MaquinariaFila>, Void>() {
            @Override
            protected List<MaquinariaFila> doInBackground() {
                return controller.listarMaquinaria(filtro, estado);
            }

            @Override
            protected void done() {
                cargando = false;
                try {
                    List<MaquinariaFila> filas = get();
                    llenarTabla(filas);
                    lblEstadoCarga.setText(filas.size() + " registro(s) mostrado(s).");
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga de maquinaria.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar la maquinaria.");
                } finally {
                    cambiarEstadoInterfaz(false);
                    if (recargaPendiente) {
                        recargaPendiente = false;
                        recargarMaquinaria();
                    }
                }
            }
        }.execute();
    }

    private void llenarTabla(List<MaquinariaFila> filas) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.clearSelection();
        modelo.setRowCount(0);
        for (MaquinariaFila maquinaria : filas) {
            String fecha = maquinaria.fechaRegistro() == null ? ""
                    : maquinaria.fechaRegistro().toLocalDateTime().format(FORMATO_FECHA);
            modelo.addRow(new Object[]{
                maquinaria.idMaquinaria(),
                maquinaria.codigoInventario(),
                maquinaria.categoria(),
                valorVisible(maquinaria.marca()),
                valorVisible(maquinaria.modelo()),
                decimalVisible(maquinaria.tonelaje()),
                decimalVisible(maquinaria.horasUso()),
                maquinaria.estadoOperativo(),
                maquinaria.activa() ? "ACTIVA" : "INACTIVA",
                fecha
            });
        }
        actualizarBotonesSeleccion();
    }

    private void crearMaquinaria() {
        if (cargando) {
            return;
        }
        CategoriaOpcion categoria = (CategoriaOpcion) cmbCategoria.getSelectedItem();
        String codigo = txtCodigo.getText();
        String marca = txtMarca.getText();
        String modelo = txtModelo.getText();
        String tonelaje = txtTonelaje.getText();
        String horas = txtHorasUso.getText();
        String estado = (String) cmbEstado.getSelectedItem();
        iniciarOperacion();
        new SwingWorker<ResultadoCreacion, Void>() {
            @Override
            protected ResultadoCreacion doInBackground() {
                return controller.crearMaquinaria(
                        categoria == null ? null : categoria.idCategoria(),
                        codigo, marca, modelo, tonelaje, horas, estado);
            }

            @Override
            protected void done() {
                terminarOperacion();
                try {
                    ResultadoCreacion resultado = get();
                    if (!resultado.exitoso()) {
                        mostrarValidacion(resultado.mensaje());
                        return;
                    }
                    limpiarFormulario();
                    JOptionPane.showMessageDialog(MAQUINARIAGESTION.this,
                            resultado.mensaje(), "Maquinaria creada",
                            JOptionPane.INFORMATION_MESSAGE);
                    recargarMaquinaria();
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la creación de maquinaria.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible crear la maquinaria.");
                }
            }
        }.execute();
    }

    private void cargarEdicionSeleccionada() {
        Integer idMaquinaria = idMaquinariaSeleccionada();
        if (idMaquinaria == null || cargando) {
            return;
        }
        iniciarOperacion();
        new SwingWorker<Optional<MaquinariaEdicion>, Void>() {
            @Override
            protected Optional<MaquinariaEdicion> doInBackground() {
                return controller.obtenerMaquinariaEdicion(idMaquinaria);
            }

            @Override
            protected void done() {
                terminarOperacion();
                try {
                    Optional<MaquinariaEdicion> maquinaria = get();
                    if (maquinaria.isEmpty()) {
                        mostrarValidacion("La maquinaria seleccionada ya no está disponible.");
                        recargarMaquinaria();
                        return;
                    }
                    mostrarFormularioEdicion(maquinaria.get());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga de maquinaria.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar la maquinaria.");
                }
            }
        }.execute();
    }

    private void mostrarFormularioEdicion(MaquinariaEdicion maquinaria) {
        JTextField codigo = new JTextField(maquinaria.codigoInventario(), 20);
        JComboBox<CategoriaOpcion> categoria = new JComboBox<>();
        DefaultComboBoxModel<CategoriaOpcion> categoriasEdicion = new DefaultComboBoxModel<>();
        for (CategoriaOpcion opcion : categorias) {
            if (opcion.activa() || opcion.idCategoria() == maquinaria.idCategoria()) {
                categoriasEdicion.addElement(opcion);
            }
        }
        categoria.setModel(categoriasEdicion);
        seleccionarCategoria(categoria, maquinaria.idCategoria());
        JTextField marca = new JTextField(valorVisible(maquinaria.marca()), 20);
        JTextField modelo = new JTextField(valorVisible(maquinaria.modelo()), 20);
        JTextField tonelaje = new JTextField(decimalVisible(maquinaria.tonelaje()), 12);
        JTextField horas = new JTextField(decimalVisible(maquinaria.horasUso()), 12);
        JComboBox<String> estado = new JComboBox<>(
                GestionMaquinariaController.ESTADOS_OPERATIVOS.toArray(String[]::new));
        estado.setSelectedItem(maquinaria.estadoOperativo());

        JPanel formulario = new JPanel(new GridBagLayout());
        formulario.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        agregarCampo(formulario, 0, "Código", codigo);
        agregarCampo(formulario, 1, "Categoría", categoria);
        agregarCampo(formulario, 2, "Marca", marca);
        agregarCampo(formulario, 3, "Modelo", modelo);
        agregarCampo(formulario, 4, "Tonelaje", tonelaje);
        agregarCampo(formulario, 5, "Horas de uso", horas);
        agregarCampo(formulario, 6, "Estado", estado);

        int respuesta = JOptionPane.showConfirmDialog(this, formulario,
                "Editar maquinaria", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        if (respuesta != JOptionPane.OK_OPTION) {
            return;
        }
        CategoriaOpcion categoriaSeleccionada =
                (CategoriaOpcion) categoria.getSelectedItem();
        actualizarMaquinaria(maquinaria.idMaquinaria(),
                categoriaSeleccionada == null ? null
                        : categoriaSeleccionada.idCategoria(),
                codigo.getText(), marca.getText(), modelo.getText(),
                tonelaje.getText(), horas.getText(),
                (String) estado.getSelectedItem());
    }

    private void actualizarMaquinaria(
            int idMaquinaria, Integer idCategoria, String codigo, String marca,
            String modelo, String tonelaje, String horas, String estado) {
        iniciarOperacion();
        new SwingWorker<ResultadoOperacion, Void>() {
            @Override
            protected ResultadoOperacion doInBackground() {
                return controller.actualizarMaquinaria(idMaquinaria, idCategoria,
                        codigo, marca, modelo, tonelaje, horas, estado);
            }

            @Override
            protected void done() {
                terminarOperacion();
                procesarResultadoOperacion(this,
                        "Se interrumpió la actualización de maquinaria.",
                        "No fue posible actualizar la maquinaria.");
            }
        }.execute();
    }

    private void cambiarEstadoSeleccionado() {
        Integer idMaquinaria = idMaquinariaSeleccionada();
        if (idMaquinaria == null || cargando) {
            return;
        }
        boolean activar = !maquinariaSeleccionadaActiva();
        String accion = activar ? "reactivar" : "desactivar";
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Deseas " + accion + " la maquinaria seleccionada?",
                activar ? "Reactivar maquinaria" : "Desactivar maquinaria",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        iniciarOperacion();
        new SwingWorker<ResultadoOperacion, Void>() {
            @Override
            protected ResultadoOperacion doInBackground() {
                return controller.cambiarEstadoRegistro(idMaquinaria, activar);
            }

            @Override
            protected void done() {
                terminarOperacion();
                procesarResultadoOperacion(this,
                        "Se interrumpió el cambio de estado de la maquinaria.",
                        "No fue posible cambiar el estado de la maquinaria.");
            }
        }.execute();
    }

    private void procesarResultadoOperacion(
            SwingWorker<ResultadoOperacion, Void> worker,
            String mensajeInterrumpido, String mensajeError) {
        try {
            ResultadoOperacion resultado = worker.get();
            if (!resultado.exitoso()) {
                mostrarValidacion(resultado.mensaje());
                return;
            }
            JOptionPane.showMessageDialog(this, resultado.mensaje(),
                    "Gestión de maquinaria", JOptionPane.INFORMATION_MESSAGE);
            recargarMaquinaria();
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            mostrarError(mensajeInterrumpido);
        } catch (ExecutionException exception) {
            mostrarError(mensajeError);
        }
    }

    private void iniciarOperacion() {
        cargando = true;
        cambiarEstadoInterfaz(true);
        lblEstadoCarga.setText("Procesando...");
    }

    private void terminarOperacion() {
        cargando = false;
        cambiarEstadoInterfaz(false);
        if ("Procesando...".equals(lblEstadoCarga.getText())) {
            lblEstadoCarga.setText("Listo.");
        }
    }

    private void cambiarEstadoInterfaz(boolean ocupado) {
        boolean hayCategorias = categorias.stream().anyMatch(CategoriaOpcion::activa)
                || cmbCategoria.getItemCount() > 0;
        txtCodigo.setEnabled(!ocupado);
        txtMarca.setEnabled(!ocupado);
        txtModelo.setEnabled(!ocupado);
        txtTonelaje.setEnabled(!ocupado);
        txtHorasUso.setEnabled(!ocupado);
        txtBuscar.setEnabled(!ocupado);
        cmbCategoria.setEnabled(!ocupado && hayCategorias);
        cmbEstado.setEnabled(!ocupado);
        cmbFiltroEstado.setEnabled(!ocupado);
        btnGuardar.setEnabled(!ocupado && hayCategorias);
        btnNuevaCategoria.setEnabled(!ocupado);
        btnLimpiar.setEnabled(!ocupado);
        btnBuscar.setEnabled(!ocupado);
        jTable1.setEnabled(!ocupado);
        actualizarBotonesSeleccion();
    }

    private void actualizarBotonesSeleccion() {
        boolean seleccionValida = jTable1.getSelectedRow() >= 0 && !cargando;
        btnEditar.setEnabled(seleccionValida);
        btnEstadoRegistro.setEnabled(seleccionValida);
        btnEstadoRegistro.setText(seleccionValida && !maquinariaSeleccionadaActiva()
                ? "REACTIVAR" : "DESACTIVAR");
    }

    private Integer idMaquinariaSeleccionada() {
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            return null;
        }
        int filaModelo = jTable1.convertRowIndexToModel(fila);
        return (Integer) jTable1.getModel().getValueAt(filaModelo, 0);
    }

    private boolean maquinariaSeleccionadaActiva() {
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            return false;
        }
        int filaModelo = jTable1.convertRowIndexToModel(fila);
        return "ACTIVA".equals(jTable1.getModel().getValueAt(filaModelo, 8));
    }

    private void limpiarFormulario() {
        txtCodigo.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtTonelaje.setText("");
        txtHorasUso.setText("");
        if (cmbCategoria.getItemCount() > 0) {
            cmbCategoria.setSelectedIndex(0);
        }
        cmbEstado.setSelectedItem("DISPONIBLE");
        txtCodigo.requestFocusInWindow();
    }

    private void seleccionarCategoria(JComboBox<CategoriaOpcion> combo, int idCategoria) {
        for (int indice = 0; indice < combo.getItemCount(); indice++) {
            if (combo.getItemAt(indice).idCategoria() == idCategoria) {
                combo.setSelectedIndex(indice);
                return;
            }
        }
    }

    private void agregarCampo(JPanel panel, int fila, String etiqueta,
                              java.awt.Component componente) {
        GridBagConstraints izquierda = restricciones(0, fila);
        izquierda.anchor = GridBagConstraints.LINE_END;
        panel.add(new JLabel(etiqueta + ":"), izquierda);
        GridBagConstraints derecha = restricciones(1, fila);
        derecha.fill = GridBagConstraints.HORIZONTAL;
        derecha.weightx = 1.0;
        panel.add(componente, derecha);
    }

    private GridBagConstraints restricciones(int columna, int fila) {
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.gridx = columna;
        constraints.gridy = fila;
        constraints.insets = new Insets(5, 6, 5, 6);
        return constraints;
    }

    private String decimalVisible(BigDecimal valor) {
        return valor == null ? "" : valor.stripTrailingZeros().toPlainString();
    }

    private String valorVisible(String valor) {
        return valor == null ? "" : valor;
    }

    private void mostrarValidacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Validación",
                JOptionPane.WARNING_MESSAGE);
    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Gestión de maquinaria",
                JOptionPane.ERROR_MESSAGE);
    }

    private record DatosIniciales(List<CategoriaOpcion> categorias,
                                  List<MaquinariaFila> maquinaria) {}

    private record ResultadoCategoriaConListado(ResultadoCategoria resultado,
                                                 List<CategoriaOpcion> categorias) {}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.titanops.vista.componentes.Boton btnBuscar;
    private com.titanops.vista.componentes.Boton btnEditar;
    private com.titanops.vista.componentes.Boton btnEstadoRegistro;
    private com.titanops.vista.componentes.Boton btnGuardar;
    private com.titanops.vista.componentes.Boton btnLimpiar;
    private com.titanops.vista.componentes.Boton btnNuevaCategoria;
    private com.titanops.vista.componentes.Selector cmbCategoria;
    private com.titanops.vista.componentes.Selector cmbEstado;
    private com.titanops.vista.componentes.Selector cmbFiltroEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.titanops.vista.componentes.Tabla jTable1;
    private javax.swing.JLabel lblCmbCategoria;
    private javax.swing.JLabel lblCmbEstado;
    private javax.swing.JLabel lblCmbFiltroEstado;
    private javax.swing.JLabel lblEstadoCarga;
    private javax.swing.JLabel lblFormulario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTxtBuscar;
    private javax.swing.JLabel lblTxtCodigo;
    private javax.swing.JLabel lblTxtHorasUso;
    private javax.swing.JLabel lblTxtMarca;
    private javax.swing.JLabel lblTxtModelo;
    private javax.swing.JLabel lblTxtTonelaje;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelAccionesCreacion;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelCreacion;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelListado;
    private com.titanops.vista.componentes.CampoTexto txtBuscar;
    private com.titanops.vista.componentes.CampoTexto txtCodigo;
    private com.titanops.vista.componentes.CampoTexto txtHorasUso;
    private com.titanops.vista.componentes.CampoTexto txtMarca;
    private com.titanops.vista.componentes.CampoTexto txtModelo;
    private com.titanops.vista.componentes.CampoTexto txtTonelaje;
    // End of variables declaration//GEN-END:variables
}
