/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.titanops.vista;

import com.titanops.controlador.GestionOperadoresController;
import com.titanops.controlador.GestionOperadoresController.OperadorEdicion;
import com.titanops.controlador.GestionOperadoresController.OperadorFila;
import com.titanops.controlador.GestionOperadoresController.ResultadoCreacion;
import com.titanops.controlador.GestionOperadoresController.ResultadoOperacion;
import com.titanops.dao.OperadorDAO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.ExecutionException;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Natha
 */
public class Operario extends javax.swing.JPanel {

    private static final DateTimeFormatter FORMATO_FECHA =
            DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    private final GestionOperadoresController controller;
    private boolean cargando;
    private boolean recargaPendiente;

    /**
     * Creates new form Operario
     */
    public Operario() {
        this(new GestionOperadoresController(new OperadorDAO()));
    }

    Operario(GestionOperadoresController controller) {
        initComponents();
        this.controller = controller;
        configurarVista();

        recargarOperadores("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenidoOperario = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        lblTxt_nombre_operario2 = new javax.swing.JLabel();
        txt_nombre_operario2 = new com.titanops.vista.componentes.CampoTexto();
        lblJComboBox1 = new javax.swing.JLabel();
        jComboBox1 = new com.titanops.vista.componentes.Selector();
        lblTxt_apellido_operario = new javax.swing.JLabel();
        txt_apellido_operario = new com.titanops.vista.componentes.CampoTexto();
        lblJComboBox2 = new javax.swing.JLabel();
        jComboBox2 = new com.titanops.vista.componentes.Selector();
        lblTxt_dui = new javax.swing.JLabel();
        txt_dui = new com.titanops.vista.componentes.CampoTexto();
        lblJComboBox3 = new javax.swing.JLabel();
        jComboBox3 = new com.titanops.vista.componentes.Selector();
        lblTxtTelefonoCreacion = new javax.swing.JLabel();
        txtTelefonoCreacion = new com.titanops.vista.componentes.CampoTexto();
        btn_operario1 = new com.titanops.vista.componentes.Boton();
        panelBuscar = new javax.swing.JPanel();
        lblTxt_nombre_operario1 = new javax.swing.JLabel();
        txt_nombre_operario1 = new com.titanops.vista.componentes.CampoTexto();
        btn_operario = new com.titanops.vista.componentes.Boton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new com.titanops.vista.componentes.Tabla();
        panelAcciones = new javax.swing.JPanel();
        btnEditar = new com.titanops.vista.componentes.Boton();
        btnEstado = new com.titanops.vista.componentes.Boton();

        setBackground(new java.awt.Color(239, 246, 255));
        setForeground(new java.awt.Color(30, 41, 59));
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(new java.awt.BorderLayout(12, 12));

        contenidoOperario.setForeground(new java.awt.Color(30, 41, 59));
        contenidoOperario.setBackground(new java.awt.Color(239, 246, 255));
        contenidoOperario.setLayout(new java.awt.BorderLayout(0, 12));

        panelSuperior.setForeground(new java.awt.Color(30, 41, 59));
        panelSuperior.setBackground(new java.awt.Color(248, 250, 252));
        panelSuperior.setLayout(new java.awt.BorderLayout(0, 12));

        panelDatos.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.setBackground(new java.awt.Color(248, 250, 252));
        panelDatos.setLayout(new java.awt.GridLayout(4, 4, 12, 10));

        lblTxt_nombre_operario2.setText("Nombres");
        lblTxt_nombre_operario2.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxt_nombre_operario2);

        txt_nombre_operario2.setForeground(new java.awt.Color(30, 41, 59));
        txt_nombre_operario2.setColorFoco(new java.awt.Color(37, 99, 235));
        txt_nombre_operario2.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txt_nombre_operario2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txt_nombre_operario2.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_nombre_operario2.setSelectionColor(new java.awt.Color(191, 219, 254));
        txt_nombre_operario2.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txt_nombre_operario2.setCaretColor(new java.awt.Color(37, 99, 235));
        txt_nombre_operario2.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txt_nombre_operario2.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txt_nombre_operario2.setPlaceholder("Nombres del operador");
        panelDatos.add(txt_nombre_operario2);

        lblJComboBox1.setText("Licencia");
        lblJComboBox1.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblJComboBox1);

        jComboBox1.setForeground(new java.awt.Color(30, 41, 59));
        jComboBox1.setColorFoco(new java.awt.Color(37, 99, 235));
        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        jComboBox1.setPreferredSize(new java.awt.Dimension(180, 30));
        panelDatos.add(jComboBox1);

        lblTxt_apellido_operario.setText("Apellidos");
        lblTxt_apellido_operario.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxt_apellido_operario);

        txt_apellido_operario.setForeground(new java.awt.Color(30, 41, 59));
        txt_apellido_operario.setColorFoco(new java.awt.Color(37, 99, 235));
        txt_apellido_operario.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txt_apellido_operario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txt_apellido_operario.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_apellido_operario.setSelectionColor(new java.awt.Color(191, 219, 254));
        txt_apellido_operario.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txt_apellido_operario.setCaretColor(new java.awt.Color(37, 99, 235));
        txt_apellido_operario.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txt_apellido_operario.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txt_apellido_operario.setPlaceholder("Apellidos del operador");
        panelDatos.add(txt_apellido_operario);

        lblJComboBox2.setText("Turno");
        lblJComboBox2.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblJComboBox2);

        jComboBox2.setForeground(new java.awt.Color(30, 41, 59));
        jComboBox2.setColorFoco(new java.awt.Color(37, 99, 235));
        jComboBox2.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        jComboBox2.setPreferredSize(new java.awt.Dimension(180, 30));
        panelDatos.add(jComboBox2);

        lblTxt_dui.setText("DUI");
        lblTxt_dui.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxt_dui);

        txt_dui.setForeground(new java.awt.Color(30, 41, 59));
        txt_dui.setColorFoco(new java.awt.Color(37, 99, 235));
        txt_dui.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txt_dui.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txt_dui.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_dui.setSelectionColor(new java.awt.Color(191, 219, 254));
        txt_dui.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txt_dui.setCaretColor(new java.awt.Color(37, 99, 235));
        txt_dui.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txt_dui.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txt_dui.setPlaceholder("DUI en formato 00000000-0");
        panelDatos.add(txt_dui);

        lblJComboBox3.setText("Estado");
        lblJComboBox3.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblJComboBox3);

        jComboBox3.setForeground(new java.awt.Color(30, 41, 59));
        jComboBox3.setColorFoco(new java.awt.Color(37, 99, 235));
        jComboBox3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8)));
        jComboBox3.setPreferredSize(new java.awt.Dimension(180, 30));
        panelDatos.add(jComboBox3);

        lblTxtTelefonoCreacion.setText("Teléfono");
        lblTxtTelefonoCreacion.setForeground(new java.awt.Color(30, 41, 59));
        panelDatos.add(lblTxtTelefonoCreacion);

        txtTelefonoCreacion.setForeground(new java.awt.Color(30, 41, 59));
        txtTelefonoCreacion.setColorFoco(new java.awt.Color(37, 99, 235));
        txtTelefonoCreacion.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtTelefonoCreacion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txtTelefonoCreacion.setPreferredSize(new java.awt.Dimension(200, 40));
        txtTelefonoCreacion.setSelectionColor(new java.awt.Color(191, 219, 254));
        txtTelefonoCreacion.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txtTelefonoCreacion.setCaretColor(new java.awt.Color(37, 99, 235));
        txtTelefonoCreacion.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txtTelefonoCreacion.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txtTelefonoCreacion.setPlaceholder("Teléfono opcional en formato 0000-0000");
        panelDatos.add(txtTelefonoCreacion);

        btn_operario1.setText("GUARDAR");
        btn_operario1.setBackground(new java.awt.Color(239, 246, 255));
        btn_operario1.setForeground(new java.awt.Color(30, 64, 175));
        btn_operario1.setFondoActivo(new java.awt.Color(37, 99, 235));
        btn_operario1.setTextoActivo(new java.awt.Color(255, 255, 255));
        btn_operario1.setColorFoco(new java.awt.Color(37, 99, 235));
        btn_operario1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btn_operario1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btn_operario1.setContentAreaFilled(false);
        btn_operario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operario1ActionPerformed(evt);
            }
        });
        panelDatos.add(btn_operario1);

        panelSuperior.add(panelDatos, java.awt.BorderLayout.CENTER);

        panelBuscar.setForeground(new java.awt.Color(30, 41, 59));
        panelBuscar.setBackground(new java.awt.Color(248, 250, 252));
        panelBuscar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 4));

        lblTxt_nombre_operario1.setText("Buscar:");
        lblTxt_nombre_operario1.setForeground(new java.awt.Color(30, 41, 59));
        panelBuscar.add(lblTxt_nombre_operario1);

        txt_nombre_operario1.setForeground(new java.awt.Color(30, 41, 59));
        txt_nombre_operario1.setColorFoco(new java.awt.Color(37, 99, 235));
        txt_nombre_operario1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txt_nombre_operario1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        txt_nombre_operario1.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_nombre_operario1.setSelectionColor(new java.awt.Color(191, 219, 254));
        txt_nombre_operario1.setSelectedTextColor(new java.awt.Color(30, 41, 59));
        txt_nombre_operario1.setCaretColor(new java.awt.Color(37, 99, 235));
        txt_nombre_operario1.setDisabledTextColor(new java.awt.Color(100, 116, 139));
        txt_nombre_operario1.setColorPlaceholder(new java.awt.Color(100, 116, 139));
        txt_nombre_operario1.setPlaceholder("Buscar por nombre, DUI, teléfono, licencia, turno o estado");
        panelBuscar.add(txt_nombre_operario1);

        btn_operario.setText("BUSCAR");
        btn_operario.setBackground(new java.awt.Color(239, 246, 255));
        btn_operario.setForeground(new java.awt.Color(30, 64, 175));
        btn_operario.setFondoActivo(new java.awt.Color(37, 99, 235));
        btn_operario.setTextoActivo(new java.awt.Color(255, 255, 255));
        btn_operario.setColorFoco(new java.awt.Color(37, 99, 235));
        btn_operario.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btn_operario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btn_operario.setContentAreaFilled(false);
        btn_operario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operarioActionPerformed(evt);
            }
        });
        panelBuscar.add(btn_operario);

        panelSuperior.add(panelBuscar, java.awt.BorderLayout.SOUTH);

        contenidoOperario.add(panelSuperior, java.awt.BorderLayout.NORTH);

        jScrollPane2.setForeground(new java.awt.Color(30, 41, 59));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)));
        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setForeground(new java.awt.Color(30, 41, 59));
        jTable1.setGridColor(new java.awt.Color(125, 211, 252));
        jTable1.setSelectionBackground(new java.awt.Color(219, 234, 254));
        jTable1.setSelectionForeground(new java.awt.Color(30, 64, 175));
        jTable1.setFondoCabecera(new java.awt.Color(224, 242, 254));
        jTable1.setTextoCabecera(new java.awt.Color(30, 64, 175));
        jTable1.setBordeCabecera(new java.awt.Color(125, 211, 252));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)));
        jTable1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jTable1.setRowHeight(30);
        jTable1.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(jTable1);

        contenidoOperario.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelAcciones.setForeground(new java.awt.Color(30, 41, 59));
        panelAcciones.setBackground(new java.awt.Color(248, 250, 252));
        panelAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 5));

        btnEditar.setText("EDITAR");
        btnEditar.setBackground(new java.awt.Color(239, 246, 255));
        btnEditar.setForeground(new java.awt.Color(30, 64, 175));
        btnEditar.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnEditar.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnEditar.setColorFoco(new java.awt.Color(37, 99, 235));
        btnEditar.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnEditar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnEditar.setContentAreaFilled(false);
        panelAcciones.add(btnEditar);

        btnEstado.setText("DESACTIVAR");
        btnEstado.setBackground(new java.awt.Color(239, 246, 255));
        btnEstado.setForeground(new java.awt.Color(30, 64, 175));
        btnEstado.setFondoActivo(new java.awt.Color(37, 99, 235));
        btnEstado.setTextoActivo(new java.awt.Color(255, 255, 255));
        btnEstado.setColorFoco(new java.awt.Color(37, 99, 235));
        btnEstado.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnEstado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        btnEstado.setContentAreaFilled(false);
        panelAcciones.add(btnEstado);

        contenidoOperario.add(panelAcciones, java.awt.BorderLayout.SOUTH);

        add(contenidoOperario, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_operarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operarioActionPerformed
       recargarOperadores(txt_nombre_operario1.getText());
    }//GEN-LAST:event_btn_operarioActionPerformed

    private void btn_operario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operario1ActionPerformed
        crearOperador();
    }//GEN-LAST:event_btn_operario1ActionPerformed

    private void configurarVista() {
        jComboBox1.setModel(new DefaultComboBoxModel<>(
                GestionOperadoresController.LICENCIAS_SUGERIDAS.toArray(String[]::new)));
        jComboBox1.setEditable(true);
        jComboBox2.setModel(new DefaultComboBoxModel<>(
                GestionOperadoresController.TURNOS.toArray(String[]::new)));
        jComboBox3.setModel(new DefaultComboBoxModel<>(new String[]{
            "DISPONIBLE", "EN_RUTA", "DESCANSO"
        }));

        DefaultTableModel modelo = new DefaultTableModel(new Object[]{
            "ID", "Nombres", "Apellidos", "DUI", "Licencia", "Turno",
            "Teléfono", "Estado operativo", "Estado del registro", "Fecha de registro"
        }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(modelo);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.getTableHeader().setReorderingAllowed(false);

        txt_nombre_operario2.setToolTipText("Nombres del operador");
        txt_apellido_operario.setToolTipText("Apellidos del operador");
        txt_dui.setToolTipText("DUI en formato 00000000-0");
        txtTelefonoCreacion.setToolTipText("Teléfono opcional en formato 0000-0000");
        txt_nombre_operario1.setToolTipText(
                "Buscar por nombre, DUI, teléfono, licencia, turno o estado");
        btn_operario1.setToolTipText("Crear operador");
        btn_operario.setToolTipText("Aplicar búsqueda");
        btnEditar.setToolTipText("Editar el operador seleccionado");
        btnEstado.setToolTipText("Desactivar o reactivar el operador seleccionado");

        txt_nombre_operario1.addActionListener(
                event -> recargarOperadores(txt_nombre_operario1.getText()));
        btnEditar.addActionListener(event -> cargarEdicionSeleccionada());
        btnEstado.addActionListener(event -> cambiarEstadoSeleccionado());
        jTable1.getSelectionModel().addListSelectionListener(
                event -> actualizarBotonesSeleccion());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent event) {
                if (event.getClickCount() == 2 && jTable1.getSelectedRow() >= 0) {
                    cargarEdicionSeleccionada();
                }
            }
        });
        actualizarBotonesSeleccion();
    }

    public final void recargarOperadores(String filtro) {
        if (cargando) {
            recargaPendiente = true;
            return;
        }
        cargando = true;
        cambiarEstadoInterfaz(true);

        new SwingWorker<List<OperadorFila>, Void>() {
            @Override
            protected List<OperadorFila> doInBackground() {
                return controller.listarOperadores(filtro);
            }

            @Override
            protected void done() {
                cargando = false;
                cambiarEstadoInterfaz(false);
                try {
                    llenarTabla(get());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga de operadores.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar los operadores.");
                } finally {
                    if (recargaPendiente) {
                        recargaPendiente = false;
                        recargarOperadores(txt_nombre_operario1.getText());
                    }
                }
            }
        }.execute();
    }

    private void llenarTabla(List<OperadorFila> operadores) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.clearSelection();
        modelo.setRowCount(0);
        for (OperadorFila operador : operadores) {
            String fecha = operador.fechaRegistro() == null ? ""
                    : operador.fechaRegistro().toLocalDateTime().format(FORMATO_FECHA);
            modelo.addRow(new Object[]{
                operador.idOperador(),
                operador.nombres(),
                operador.apellidos(),
                operador.dui(),
                operador.licenciaTipo(),
                operador.turno(),
                operador.telefono() == null ? "" : operador.telefono(),
                operador.estadoOperativo(),
                operador.activo() ? "ACTIVO" : "INACTIVO",
                fecha
            });
        }
        actualizarBotonesSeleccion();
    }

    private void crearOperador() {
        if (cargando) {
            return;
        }
        String nombres = txt_nombre_operario2.getText();
        String apellidos = txt_apellido_operario.getText();
        String dui = txt_dui.getText();
        String licencia = valorCombo(jComboBox1);
        String turno = valorCombo(jComboBox2);
        String estado = valorCombo(jComboBox3);
        String telefono = txtTelefonoCreacion.getText();
        cargando = true;
        cambiarEstadoInterfaz(true);

        new SwingWorker<ResultadoCreacion, Void>() {
            @Override
            protected ResultadoCreacion doInBackground() {
                return controller.crearOperador(
                        nombres, apellidos, dui, licencia, turno, telefono, estado);
            }

            @Override
            protected void done() {
                cargando = false;
                cambiarEstadoInterfaz(false);
                try {
                    ResultadoCreacion resultado = get();
                    if (!resultado.exitoso()) {
                        mostrarValidacion(resultado.mensaje());
                        return;
                    }
                    limpiarFormularioCreacion();
                    JOptionPane.showMessageDialog(Operario.this, resultado.mensaje(),
                            "Operador creado", JOptionPane.INFORMATION_MESSAGE);
                    recargarOperadores(txt_nombre_operario1.getText());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la creación del operador.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible crear el operador.");
                }
            }
        }.execute();
    }

    private void cargarEdicionSeleccionada() {
        Integer idOperador = idOperadorSeleccionado();
        if (idOperador == null || cargando) {
            return;
        }
        cargando = true;
        cambiarEstadoInterfaz(true);

        new SwingWorker<Optional<OperadorEdicion>, Void>() {
            @Override
            protected Optional<OperadorEdicion> doInBackground() {
                return controller.obtenerOperadorEdicion(idOperador);
            }

            @Override
            protected void done() {
                cargando = false;
                cambiarEstadoInterfaz(false);
                try {
                    Optional<OperadorEdicion> operador = get();
                    if (operador.isEmpty()) {
                        mostrarValidacion("El operador seleccionado ya no está disponible.");
                        recargarOperadores(txt_nombre_operario1.getText());
                        return;
                    }
                    mostrarFormularioEdicion(operador.get());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la carga del operador.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cargar el operador.");
                }
            }
        }.execute();
    }

    private void mostrarFormularioEdicion(OperadorEdicion operador) {
        JTextField nombres = new JTextField(operador.nombres(), 24);
        JTextField apellidos = new JTextField(operador.apellidos(), 24);
        JTextField dui = new JTextField(operador.dui(), 12);
        JComboBox<String> licencia = new JComboBox<>(
                GestionOperadoresController.LICENCIAS_SUGERIDAS.toArray(String[]::new));
        licencia.setEditable(true);
        licencia.setSelectedItem(operador.licenciaTipo());
        JComboBox<String> turno = new JComboBox<>(
                GestionOperadoresController.TURNOS.toArray(String[]::new));
        turno.setSelectedItem(operador.turno());
        JTextField telefono = new JTextField(
                operador.telefono() == null ? "" : operador.telefono(), 12);
        JComboBox<String> estado = new JComboBox<>(
                new String[]{"DISPONIBLE", "EN_RUTA", "DESCANSO"});
        estado.setSelectedItem(operador.activo()
                ? operador.estadoOperativo() : "DISPONIBLE");

        JPanel formulario = new JPanel(new GridBagLayout());
        formulario.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        agregarCampo(formulario, 0, "Nombres", nombres);
        agregarCampo(formulario, 1, "Apellidos", apellidos);
        agregarCampo(formulario, 2, "DUI", dui);
        agregarCampo(formulario, 3, "Licencia", licencia);
        agregarCampo(formulario, 4, "Turno", turno);
        agregarCampo(formulario, 5, "Teléfono (opcional)", telefono);
        agregarCampo(formulario, 6, "Estado operativo", estado);
        if (!operador.activo()) {
            GridBagConstraints aviso = restricciones(0, 7);
            aviso.gridwidth = 2;
            formulario.add(new JLabel(
                    "El operador seguirá inactivo hasta usar la acción REACTIVAR."), aviso);
        }

        int respuesta = JOptionPane.showConfirmDialog(this, formulario,
                "Editar operador", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        if (respuesta != JOptionPane.OK_OPTION) {
            return;
        }
        actualizarOperador(operador.idOperador(), nombres.getText(), apellidos.getText(),
                dui.getText(), valorCombo(licencia), valorCombo(turno),
                telefono.getText(), valorCombo(estado));
    }

    private void actualizarOperador(int idOperador, String nombres, String apellidos,
                                    String dui, String licencia, String turno,
                                    String telefono, String estado) {
        cargando = true;
        cambiarEstadoInterfaz(true);
        new SwingWorker<ResultadoOperacion, Void>() {
            @Override
            protected ResultadoOperacion doInBackground() {
                return controller.actualizarOperador(idOperador, nombres, apellidos, dui,
                        licencia, turno, telefono, estado);
            }

            @Override
            protected void done() {
                cargando = false;
                cambiarEstadoInterfaz(false);
                try {
                    ResultadoOperacion resultado = get();
                    if (!resultado.exitoso()) {
                        mostrarValidacion(resultado.mensaje());
                        return;
                    }
                    JOptionPane.showMessageDialog(Operario.this, resultado.mensaje(),
                            "Gestión de operadores", JOptionPane.INFORMATION_MESSAGE);
                    recargarOperadores(txt_nombre_operario1.getText());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió la actualización del operador.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible actualizar el operador.");
                }
            }
        }.execute();
    }

    private void cambiarEstadoSeleccionado() {
        Integer idOperador = idOperadorSeleccionado();
        if (idOperador == null || cargando) {
            return;
        }
        boolean activar = !operadorSeleccionadoActivo();
        String accion = activar ? "reactivar" : "desactivar";
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Deseas " + accion + " el operador seleccionado?",
                activar ? "Reactivar operador" : "Desactivar operador",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        cargando = true;
        cambiarEstadoInterfaz(true);
        new SwingWorker<ResultadoOperacion, Void>() {
            @Override
            protected ResultadoOperacion doInBackground() {
                return controller.cambiarEstadoOperador(idOperador, activar);
            }

            @Override
            protected void done() {
                cargando = false;
                cambiarEstadoInterfaz(false);
                try {
                    ResultadoOperacion resultado = get();
                    if (!resultado.exitoso()) {
                        mostrarValidacion(resultado.mensaje());
                        return;
                    }
                    JOptionPane.showMessageDialog(Operario.this, resultado.mensaje(),
                            "Gestión de operadores", JOptionPane.INFORMATION_MESSAGE);
                    recargarOperadores(txt_nombre_operario1.getText());
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    mostrarError("Se interrumpió el cambio de estado del operador.");
                } catch (ExecutionException exception) {
                    mostrarError("No fue posible cambiar el estado del operador.");
                }
            }
        }.execute();
    }

    private void cambiarEstadoInterfaz(boolean ocupado) {
        txt_nombre_operario2.setEnabled(!ocupado);
        txt_apellido_operario.setEnabled(!ocupado);
        txt_dui.setEnabled(!ocupado);
        txtTelefonoCreacion.setEnabled(!ocupado);
        txt_nombre_operario1.setEnabled(!ocupado);
        jComboBox1.setEnabled(!ocupado);
        jComboBox2.setEnabled(!ocupado);
        jComboBox3.setEnabled(!ocupado);
        btn_operario.setEnabled(!ocupado);
        btn_operario1.setEnabled(!ocupado);
        jTable1.setEnabled(!ocupado);
        actualizarBotonesSeleccion();
    }

    private void actualizarBotonesSeleccion() {
        boolean seleccionValida = jTable1.getSelectedRow() >= 0 && !cargando;
        btnEditar.setEnabled(seleccionValida);
        btnEstado.setEnabled(seleccionValida);
        btnEstado.setText(seleccionValida && !operadorSeleccionadoActivo()
                ? "REACTIVAR" : "DESACTIVAR");
    }

    private Integer idOperadorSeleccionado() {
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            return null;
        }
        int filaModelo = jTable1.convertRowIndexToModel(fila);
        return (Integer) jTable1.getModel().getValueAt(filaModelo, 0);
    }

    private boolean operadorSeleccionadoActivo() {
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            return false;
        }
        int filaModelo = jTable1.convertRowIndexToModel(fila);
        return "ACTIVO".equals(jTable1.getModel().getValueAt(filaModelo, 8));
    }

    private void limpiarFormularioCreacion() {
        txt_nombre_operario2.setText("");
        txt_apellido_operario.setText("");
        txt_dui.setText("");
        txtTelefonoCreacion.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        txt_nombre_operario2.requestFocusInWindow();
    }

    private String valorCombo(JComboBox<String> combo) {
        Object valor = combo.isEditable() ? combo.getEditor().getItem()
                : combo.getSelectedItem();
        return valor == null ? "" : valor.toString();
    }

    private void agregarCampo(JPanel panel, int fila, String etiqueta,
                              java.awt.Component componente) {
        GridBagConstraints izquierda = restricciones(0, fila);
        izquierda.anchor = GridBagConstraints.LINE_END;
        panel.add(new JLabel(etiqueta + ":"), izquierda);
        GridBagConstraints derecha = restricciones(1, fila);
        derecha.fill = GridBagConstraints.HORIZONTAL;
        derecha.weightx = 1.0;
        panel.add(componente, derecha);
    }

    private GridBagConstraints restricciones(int columna, int fila) {
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.gridx = columna;
        constraints.gridy = fila;
        constraints.insets = new Insets(4, 6, 4, 6);
        return constraints;
    }

    private void mostrarValidacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Validación",
                JOptionPane.WARNING_MESSAGE);
    }

    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Gestión de operadores",
                JOptionPane.ERROR_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.titanops.vista.componentes.Boton btnEditar;
    private com.titanops.vista.componentes.Boton btnEstado;
    private com.titanops.vista.componentes.Boton btn_operario;
    private com.titanops.vista.componentes.Boton btn_operario1;
    private javax.swing.JPanel contenidoOperario;
    private com.titanops.vista.componentes.Selector jComboBox1;
    private com.titanops.vista.componentes.Selector jComboBox2;
    private com.titanops.vista.componentes.Selector jComboBox3;
    private javax.swing.JScrollPane jScrollPane2;
    private com.titanops.vista.componentes.Tabla jTable1;
    private javax.swing.JLabel lblJComboBox1;
    private javax.swing.JLabel lblJComboBox2;
    private javax.swing.JLabel lblJComboBox3;
    private javax.swing.JLabel lblTxtTelefonoCreacion;
    private javax.swing.JLabel lblTxt_apellido_operario;
    private javax.swing.JLabel lblTxt_dui;
    private javax.swing.JLabel lblTxt_nombre_operario1;
    private javax.swing.JLabel lblTxt_nombre_operario2;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelSuperior;
    private com.titanops.vista.componentes.CampoTexto txtTelefonoCreacion;
    private com.titanops.vista.componentes.CampoTexto txt_apellido_operario;
    private com.titanops.vista.componentes.CampoTexto txt_dui;
    private com.titanops.vista.componentes.CampoTexto txt_nombre_operario1;
    private com.titanops.vista.componentes.CampoTexto txt_nombre_operario2;
    // End of variables declaration//GEN-END:variables
}
