/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.titanops.vista;

import com.titanops.reporte.ReporteEstadoMaquinaria;
import com.titanops.reporte.ReporteEstadoMaquinariaExporter;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Natha
 */
public class tipo_exportar extends javax.swing.JInternalFrame {
    private final ReporteEstadoMaquinaria reporte;

    /**
     * Creates new form tipo_exportar
     */
    public tipo_exportar() {
        this(null);
    }

    public tipo_exportar(ReporteEstadoMaquinaria reporte) {
        initComponents();
        this.reporte = reporte;

        configurarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GUARDARUS = new com.titanops.vista.componentes.Boton();
        GUARDARUS2 = new com.titanops.vista.componentes.Boton();
        GUARDARUS1 = new com.titanops.vista.componentes.Boton();

        setBackground(new java.awt.Color(239, 246, 255));
        setClosable(true);
        setForeground(new java.awt.Color(30, 41, 59));
        setMaximizable(true);
        setResizable(true);

        jPanel1.setForeground(new java.awt.Color(30, 41, 59));
        jPanel1.setBackground(new java.awt.Color(239, 246, 255));

        jPanel3.setForeground(new java.awt.Color(30, 41, 59));
        jPanel3.setBackground(new java.awt.Color(30, 64, 175));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("EXPORTAR REPORTE");
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );

        GUARDARUS.setText("CSV");
        GUARDARUS.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        GUARDARUS.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS.setContentAreaFilled(false);

        GUARDARUS2.setText("JSON");
        GUARDARUS2.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS2.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS2.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS2.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS2.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        GUARDARUS2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS2.setContentAreaFilled(false);

        GUARDARUS1.setText("PDF");
        GUARDARUS1.setBackground(new java.awt.Color(239, 246, 255));
        GUARDARUS1.setForeground(new java.awt.Color(30, 64, 175));
        GUARDARUS1.setFondoActivo(new java.awt.Color(37, 99, 235));
        GUARDARUS1.setTextoActivo(new java.awt.Color(255, 255, 255));
        GUARDARUS1.setColorFoco(new java.awt.Color(37, 99, 235));
        GUARDARUS1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        GUARDARUS1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 211, 252)), javax.swing.BorderFactory.createEmptyBorder(8, 14, 8, 14)));
        GUARDARUS1.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addComponent(GUARDARUS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GUARDARUS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GUARDARUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GUARDARUS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUARDARUS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GUARDARUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarEventos() {
        GUARDARUS.addActionListener(event -> exportar("CSV"));
        GUARDARUS2.addActionListener(event -> exportar("JSON"));
        GUARDARUS1.addActionListener(event -> exportar("PDF"));
    }

    private void exportar(String formato) {
        if (reporte == null) {
            JOptionPane.showMessageDialog(this,
                    "Abra la exportación desde el reporte de estado de maquinaria.",
                    "Exportar reporte", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Guardar reporte " + formato);
        selector.setSelectedFile(new File("reporte_estado_maquinaria."
                + formato.toLowerCase()));
        if (selector.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        Path destino = agregarExtension(selector.getSelectedFile().toPath(), formato);
        if (Files.exists(destino)) {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "El archivo ya existe. ¿Deseas reemplazarlo?",
                    "Confirmar reemplazo", JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if (respuesta != JOptionPane.YES_OPTION) {
                return;
            }
        }

        try {
            switch (formato) {
                case "CSV" -> ReporteEstadoMaquinariaExporter.exportarCsv(destino, reporte);
                case "JSON" -> ReporteEstadoMaquinariaExporter.exportarJson(destino, reporte);
                case "PDF" -> ReporteEstadoMaquinariaExporter.exportarPdf(destino, reporte);
                default -> throw new IOException("Formato no soportado: " + formato);
            }
            JOptionPane.showMessageDialog(this,
                    "Reporte exportado en:\n" + destino,
                    "Exportar reporte", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException exception) {
            JOptionPane.showMessageDialog(this,
                    "No fue posible exportar el reporte:\n" + exception.getMessage(),
                    "Exportar reporte", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Path agregarExtension(Path destino, String formato) {
        String extension = "." + formato.toLowerCase();
        String nombre = destino.getFileName().toString();
        return nombre.toLowerCase().endsWith(extension)
                ? destino : destino.resolveSibling(nombre + extension);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.titanops.vista.componentes.Boton GUARDARUS;
    private com.titanops.vista.componentes.Boton GUARDARUS1;
    private com.titanops.vista.componentes.Boton GUARDARUS2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
